import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'happy-dom',
    globals: true,
    setupFiles: ['./tests/setup.ts'],
    include: ['tests/unit/**/*.test.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      include: ['src/**/*.{ts,tsx}'],
      // src/types/** is generated by `cargo xtask regenerate-types` from
      // schemas/event.v1.json (per CLAUDE.md §14); type-only declarations
      // have no runtime statements to cover, so excluding the directory
      // avoids 0% display anomalies that have no behavioral signal.
      exclude: ['src/**/*.d.ts', 'src/main.tsx', 'src/types/**'],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 80,
        statements: 80,
      },
    },
  },
});
