// AUTO-GENERATED FILE — DO NOT EDIT
//
// Regenerate with: `cargo xtask regenerate-types`
// Source schema:   schemas/event.v1.json
// Generated by:    json-schema-to-typescript
//
// Drift detection runs in CI via `cargo xtask regenerate-types --check`.

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Canonical AgentEvent union emitted by the runtime. Source-of-truth for renderer TypeScript types (generated via `cargo xtask regenerate-types`). Mirrors `runtime_core::event::AgentEvent` (crates/runtime-core/src/event.rs). Variants span spec sections §2 (session/agent/tool/skill/stream/decision/token), §3a (plan/task), §3b (mode), §4a (verify+rails), §4b (gap), §6a (HITL), §8.security (capability), §2a (budget). Variants the v0.1 runtime does not yet emit are still defined here so future milestones extend the union additively.
 */
export type AgentEvent =
  | SessionStart
  | SessionEnd
  | AgentSpawned
  | AgentComplete
  | AgentError
  | ToolInvoked
  | ToolResult
  | ToolError
  | SkillLoaded
  | PlanCreated
  | PlanApprovalRequested
  | PlanApproved
  | PlanRevised
  | PlanAborted
  | PlanComplete
  | TaskStarted
  | TaskCompleted
  | TaskFailed
  | TaskSkipped
  | TaskRolledBack
  | TaskEscalated
  | ModeChanged
  | VerifyStarted
  | VerifyPassed
  | VerifyFailed
  | RailTriggered
  | SkillMissing
  | ToolMissing
  | GapResolved
  | HitlRequested
  | HitlResolved
  | CapabilityViolation
  | CapabilityGrant
  | BudgetWarn
  | BudgetDownshift
  | BudgetSuspended
  | BudgetExceeded
  | StreamText
  | DecisionRecord
  | TokenUsage;
/**
 * Origin of a tool invocation. Spec §0b + §2.
 */
export type ToolSource = "builtin" | "mcp" | "generated";
/**
 * Source of the plan approval. `user` = HITL approval seam resolved by the renderer; `auto` = framework JSON declared `approval_required: false`.
 */
export type ApprovedBy = "user" | "auto";
/**
 * Hook category — spec §4a. Mirrors common.v1.json HookCategory; embedded in verify_started events.
 */
export type HookCategoryRef = "verify" | "lint" | "build" | "test" | "custom";
/**
 * Hook on_failure policy — spec §4a. Mirrors common.v1.json HookOnFailure; embedded in verify_failed events.
 */
export type OnFailureRef = "block" | "warn" | "rollback";
/**
 * Rail policy — spec §4a. Hard rails block; soft rails warn.
 */
export type RailPolicy = "hard" | "soft";

export interface SessionStart {
  type: "session_start";
  session_id: string;
  framework: string;
  model: string;
}
export interface SessionEnd {
  type: "session_end";
  session_id: string;
  duration_ms: number;
  end_reason: string;
}
export interface AgentSpawned {
  type: "agent_spawned";
  agent_id: string;
  agent_name: string;
  parent_id?: string | null;
  session_id: string;
}
export interface AgentComplete {
  type: "agent_complete";
  agent_id: string;
  result: string;
  tokens_total?: number | null;
}
export interface AgentError {
  type: "agent_error";
  agent_id: string;
  error: string;
}
export interface ToolInvoked {
  type: "tool_invoked";
  agent_id: string;
  tool_name: string;
  source: ToolSource;
  server?: string | null;
  input: unknown;
}
export interface ToolResult {
  type: "tool_result";
  agent_id: string;
  tool_name: string;
  output: unknown;
  duration_ms: number;
  tokens_in?: number | null;
  tokens_out?: number | null;
}
export interface ToolError {
  type: "tool_error";
  agent_id: string;
  tool_name: string;
  error: string;
}
export interface SkillLoaded {
  type: "skill_loaded";
  agent_id: string;
  skill_name: string;
  mode?: string | null;
}
export interface PlanCreated {
  type: "plan_created";
  plan_id: string;
  title: string;
  task_count: number;
  approval_required: boolean;
}
export interface PlanApprovalRequested {
  type: "plan_approval_requested";
  plan_id: string;
}
export interface PlanApproved {
  type: "plan_approved";
  plan_id: string;
  approved_by: ApprovedBy;
}
export interface PlanRevised {
  type: "plan_revised";
  plan_id: string;
  revision_reason: string;
}
export interface PlanAborted {
  type: "plan_aborted";
  plan_id: string;
  reason: string;
}
export interface PlanComplete {
  type: "plan_complete";
  plan_id: string;
  duration_ms: number;
}
export interface TaskStarted {
  type: "task_started";
  plan_id: string;
  task_id: string;
  agent_id: string;
}
export interface TaskCompleted {
  type: "task_completed";
  plan_id: string;
  task_id: string;
  duration_ms: number;
}
export interface TaskFailed {
  type: "task_failed";
  plan_id: string;
  task_id: string;
  error: string;
  failure_count: number;
}
export interface TaskSkipped {
  type: "task_skipped";
  plan_id: string;
  task_id: string;
  reason: string;
}
export interface TaskRolledBack {
  type: "task_rolled_back";
  plan_id: string;
  task_id: string;
  snapshot_id: string;
}
export interface TaskEscalated {
  type: "task_escalated";
  plan_id: string;
  task_id: string;
  failure_count: number;
  max_failures: number;
}
export interface ModeChanged {
  type: "mode_changed";
  from: string;
  to: string;
  reason: string;
}
export interface VerifyStarted {
  type: "verify_started";
  hook_id: string;
  category: HookCategoryRef;
  firing_point: string;
  level?: string | null;
}
export interface VerifyPassed {
  type: "verify_passed";
  hook_id: string;
  duration_ms: number;
  output_preview?: string | null;
}
export interface VerifyFailed {
  type: "verify_failed";
  hook_id: string;
  duration_ms: number;
  error: string;
  on_failure: OnFailureRef;
}
export interface RailTriggered {
  type: "rail_triggered";
  rail_id: string;
  policy: RailPolicy;
  firing_point: string;
  message: string;
  agent_id?: string | null;
}
export interface SkillMissing {
  type: "skill_missing";
  agent_id: string;
  skill_name: string;
  severity: string;
}
export interface ToolMissing {
  type: "tool_missing";
  agent_id: string;
  tool_name: string;
  severity: string;
}
export interface GapResolved {
  type: "gap_resolved";
  agent_id: string;
  capability: string;
  kind: string;
}
export interface HitlRequested {
  type: "hitl_requested";
  agent_id: string;
  prompt: string;
  hitl_kind: string;
}
export interface HitlResolved {
  type: "hitl_resolved";
  agent_id: string;
  response: string;
  duration_ms: number;
}
export interface CapabilityViolation {
  type: "capability_violation";
  agent_id: string;
  declared: string;
  attempted: string;
}
export interface CapabilityGrant {
  type: "capability_grant";
  agent_id: string;
  capability: string;
  scope: string;
}
export interface BudgetWarn {
  type: "budget_warn";
  spent_usd: number;
  cap_usd: number;
  percent: number;
}
export interface BudgetDownshift {
  type: "budget_downshift";
  from_model: string;
  to_model: string;
  reason: string;
}
export interface BudgetSuspended {
  type: "budget_suspended";
  spent_usd: number;
  cap_usd: number;
}
export interface BudgetExceeded {
  type: "budget_exceeded";
  spent_usd: number;
  cap_usd: number;
}
export interface StreamText {
  type: "stream_text";
  agent_id: string;
  text: string;
}
export interface DecisionRecord {
  type: "decision_record";
  agent_id: string;
  decision: string;
  rationale: string;
  tool_used?: string | null;
}
export interface TokenUsage {
  type: "token_usage";
  input: number;
  output: number;
  model: string;
  cost_usd: number;
}
