// AUTO-GENERATED FILE — DO NOT EDIT
//
// Regenerate with: `cargo xtask regenerate-types`
// Source schema:   schemas/event.v1.json
// Generated by:    json-schema-to-typescript
//
// Drift detection runs in CI via `cargo xtask regenerate-types --check`.

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Canonical AgentEvent union emitted by the runtime. Source-of-truth for renderer TypeScript types (generated via `cargo xtask regenerate-types`). Mirrors `runtime_core::event::AgentEvent` (crates/runtime-core/src/event.rs). Variants span spec sections §2 (session/agent/tool/skill/stream/decision/token), §3a (plan/task), §3b (mode), §4a (verify+rails), §4b (gap), §6a (HITL), §8.security (capability), §2a (budget). Variants the v0.1 runtime does not yet emit are still defined here so future milestones extend the union additively.
 */
export type AgentEvent =
  | SessionStart
  | SessionEnd
  | AgentSpawned
  | AgentComplete
  | AgentError
  | ToolInvoked
  | ToolResult
  | ToolError
  | SkillLoaded
  | PlanCreated
  | PlanApprovalRequested
  | PlanApproved
  | PlanRevised
  | PlanAborted
  | PlanComplete
  | TaskStarted
  | TaskCompleted
  | TaskFailed
  | TaskSkipped
  | TaskRolledBack
  | TaskEscalated
  | ModeChanged
  | VerifyStarted
  | VerifyPassed
  | VerifyFailed
  | RailTriggered
  | SkillMissing
  | ToolMissing
  | McpMissing
  | AgentMissing
  | GapResolved
  | HitlRequested
  | HitlResolved
  | HitlTimeout
  | NotifierDispatched
  | NotifierFailed
  | CapabilityViolation
  | CapabilityGrant
  | BudgetWarn
  | BudgetDownshift
  | BudgetSuspended
  | BudgetExceeded
  | StreamText
  | DecisionRecord
  | TierViolation
  | TierTransition
  | TokenUsage;
/**
 * One short, human-readable description of a parent capability that the L2a narrowing seam considered when computing a child's narrowed grants. Format is emitter-defined (e.g., `read:src:glob:src/**`); renderer surfaces verbatim. Per gotcha #43 (typify-friendly extraction): inline-validated strings inside oneOf variants must be extracted to $defs with a title or typify panics.
 */
export type NarrowedFromGrantDescription = string;
/**
 * Origin of a tool invocation. Spec §0b + §2.
 */
export type ToolSource = "builtin" | "mcp" | "generated";
/**
 * Source of the plan approval. `user` = HITL approval seam resolved by the renderer; `auto` = framework JSON declared `approval_required: false`.
 */
export type ApprovedBy = "user" | "auto";
/**
 * Hook category — spec §4a. Mirrors common.v1.json HookCategory; embedded in verify_started events.
 */
export type HookCategoryRef = "verify" | "lint" | "build" | "test" | "custom";
/**
 * Hook on_failure policy — spec §4a. Mirrors common.v1.json HookOnFailure; embedded in verify_failed events.
 */
export type OnFailureRef = "block" | "warn" | "rollback";
/**
 * Rail policy — spec §4a. Hard rails block; soft rails warn.
 */
export type RailPolicy = "hard" | "soft";
/**
 * Severity matrix per spec §4b. `critical` blocks the session (loader-detected tool gaps; agent_missing); `important` blocks the owning agent but lets the session continue (request_capability tool gaps); `advisory` warns and continues (skill gaps from any source); `requested` is the M05 marker for request_capability-emitted gaps so the renderer can distinguish loader vs meta-tool origin in the same severity tier.
 */
export type GapSeverity = "critical" | "important" | "advisory" | "requested";
/**
 * Plain-English next-step text the renderer surfaces in the GapPanel + HITL prompt. Free-form; emitter composes per severity (e.g. "Install tool 'fetch_prs' and click Resume" for critical; "Skill 'rag' continues without — install async or dismiss" for advisory). minLength 1 — emitters MUST supply a non-empty action.
 */
export type SuggestedAction = string;
/**
 * How this gap was discovered. `loader` = the framework_loader walked the framework JSON at session start and the reference did not resolve. `request_capability` = a running agent asked for the capability mid-session via the meta-tool. Drives renderer display + HITL prompt copy.
 */
export type GapSource = "loader" | "request_capability";
/**
 * HITL trigger discriminator embedded in HITL + notifier events. Spec §6a — mirrors hitl.v1.json HitlTrigger (9 values, locked). The mirror exists because typify does not support cross-schema $ref to enums; per-schema $defs duplication is the established M04.D pattern (HookCategoryRef, OnFailureRef, RailPolicy).
 */
export type HitlTriggerRef =
  | "on_gap"
  | "on_risky_tool"
  | "on_dont_touch_edit"
  | "on_failure_threshold"
  | "on_capability_violation"
  | "on_budget_threshold"
  | "on_plan_approval"
  | "per_task"
  | "per_epic";
/**
 * HITL UI variant discriminator embedded in `hitl_requested` events. Spec §6a — mirrors hitl.v1.json HitlUiVariant.
 */
export type HitlUiVariantRef = "panel" | "modal" | "toast";
/**
 * Coarse category of access the attempted dispatch needed.
 */
export type CapabilityKindRef = "read" | "write" | "exec" | "network" | "process_spawn";
/**
 * Plain-English description of what the agent attempted; surfaced in the HITL prompt + capability-violation modal so the user understands the rejection. Per gotcha #43 (typify-friendly extraction): validated inline strings inside oneOf variants are extracted to $defs with a title.
 */
export type RequestedAction = string;
/**
 * Plain-English description of the scope the agent's grants cover. Renderer pairs with `requested_action` to surface the mismatch (e.g., grants cover `src/**` glob; request targeted `~/.ssh/keys`). Per gotcha #43 (typify-friendly extraction).
 */
export type DeclaredScope = string;
/**
 * Capability-kind discriminator embedded in capability_violation + capability_grant events. Spec §8.security L1 — mirrors capability.v1.json CapabilityKind (5 values, locked). The mirror exists because typify does not support cross-schema $ref to enums; per-schema $defs duplication is the established M04.D pattern (HookCategoryRef, OnFailureRef, RailPolicy, HitlTriggerRef, GapSeverityRef).
 */
export type CapabilityKindRef1 = "read" | "write" | "exec" | "network" | "process_spawn";
/**
 * Resource name the grant covers — tool name, file glob, network hostname, or sub-agent id depending on `capability_kind`. Per gotcha #43 (typify-friendly extraction).
 */
export type GrantedResource = string;
/**
 * User tier discriminator — spec §8.security L4 + §0d release scope (M05 Stage D). Two-tier system in v0.1: `novice` (curated allowlist — read + HTTPS-only network) is the first-run default; `promoted` (full capability surface; L1 still narrows) is the user-toggled tier. Full tier is post-v0.1. The mirror exists because typify does not support cross-schema $ref to enums; per-schema $defs duplication is the established M04.D pattern (HookCategoryRef, OnFailureRef, RailPolicy, HitlTriggerRef, CapabilityKindRef).
 */
export type TierRef = "novice" | "promoted";
/**
 * Capability-kind discriminator embedded in capability_violation + capability_grant events. Spec §8.security L1 — mirrors capability.v1.json CapabilityKind (5 values, locked). The mirror exists because typify does not support cross-schema $ref to enums; per-schema $defs duplication is the established M04.D pattern (HookCategoryRef, OnFailureRef, RailPolicy, HitlTriggerRef, GapSeverityRef).
 */
export type CapabilityKindRef2 = "read" | "write" | "exec" | "network" | "process_spawn";
/**
 * Plain-English description of what the agent attempted; surfaced in the tier-violation modal so the user understands the rejection. Pairs with `capability_kind` (e.g., "attempted to write to src/lib.rs while in Novice tier"). Per gotcha #43 (typify-friendly extraction).
 */
export type TierForbiddenAction = string;
/**
 * Plain-English reason for the tier transition. For promotions: user clicked confirm in the Settings panel. For demotions: user clicked demote OR a downgrade-on-uncertainty affordance fired. Per gotcha #43 (typify-friendly extraction).
 */
export type TierTransitionReason = string;

export interface SessionStart {
  type: "session_start";
  session_id: string;
  framework: string;
  model: string;
}
export interface SessionEnd {
  type: "session_end";
  session_id: string;
  duration_ms: number;
  end_reason: string;
}
export interface AgentSpawned {
  type: "agent_spawned";
  agent_id: string;
  agent_name: string;
  parent_id?: string | null;
  session_id: string;
  /**
   * Optional — when this spawn passed L2a narrowing (M06 Stage A wire-up of the M05.B `narrow` primitive at the framework-loader walk site), carries one short human-readable description per proposed (pre-narrow) child capability so the renderer's AgentNode debug inspector can surface 'spawned with narrowed scope' attribution per §8.security L2a. Absent for top-level agents (no parent grants to narrow against) or for spawns that did not flow through the narrowing seam (e.g., the M02 smoke session that pre-dates the wire-up). Present (even as an empty array) signals 'this spawn was gated by L2a'. Per the M04.D mirror-not-cross-schema-ref pattern (CapabilityKindRef etc.) — Vec<String> over Vec<CapabilityDeclaration> avoids cross-schema $ref friction in the json-schema-to-typescript pipeline; the underlying CapabilityDeclaration data is serialized to its `kind:resource:scope:side_effect_class` string form at emit time.
   */
  narrowed_from?: NarrowedFromGrantDescription[];
}
export interface AgentComplete {
  type: "agent_complete";
  agent_id: string;
  result: string;
  tokens_total?: number | null;
}
export interface AgentError {
  type: "agent_error";
  agent_id: string;
  error: string;
}
export interface ToolInvoked {
  type: "tool_invoked";
  agent_id: string;
  tool_name: string;
  source: ToolSource;
  server?: string | null;
  input: unknown;
}
export interface ToolResult {
  type: "tool_result";
  agent_id: string;
  tool_name: string;
  output: unknown;
  duration_ms: number;
  tokens_in?: number | null;
  tokens_out?: number | null;
}
export interface ToolError {
  type: "tool_error";
  agent_id: string;
  tool_name: string;
  error: string;
}
export interface SkillLoaded {
  type: "skill_loaded";
  agent_id: string;
  skill_name: string;
  mode?: string | null;
}
export interface PlanCreated {
  type: "plan_created";
  plan_id: string;
  title: string;
  task_count: number;
  approval_required: boolean;
}
export interface PlanApprovalRequested {
  type: "plan_approval_requested";
  plan_id: string;
}
export interface PlanApproved {
  type: "plan_approved";
  plan_id: string;
  approved_by: ApprovedBy;
}
export interface PlanRevised {
  type: "plan_revised";
  plan_id: string;
  revision_reason: string;
}
export interface PlanAborted {
  type: "plan_aborted";
  plan_id: string;
  reason: string;
}
export interface PlanComplete {
  type: "plan_complete";
  plan_id: string;
  duration_ms: number;
}
export interface TaskStarted {
  type: "task_started";
  plan_id: string;
  task_id: string;
  agent_id: string;
}
export interface TaskCompleted {
  type: "task_completed";
  plan_id: string;
  task_id: string;
  duration_ms: number;
}
export interface TaskFailed {
  type: "task_failed";
  plan_id: string;
  task_id: string;
  error: string;
  failure_count: number;
}
export interface TaskSkipped {
  type: "task_skipped";
  plan_id: string;
  task_id: string;
  reason: string;
}
export interface TaskRolledBack {
  type: "task_rolled_back";
  plan_id: string;
  task_id: string;
  snapshot_id: string;
}
export interface TaskEscalated {
  type: "task_escalated";
  plan_id: string;
  task_id: string;
  failure_count: number;
  max_failures: number;
}
export interface ModeChanged {
  type: "mode_changed";
  from: string;
  to: string;
  reason: string;
}
export interface VerifyStarted {
  type: "verify_started";
  hook_id: string;
  category: HookCategoryRef;
  firing_point: string;
  level?: string | null;
}
export interface VerifyPassed {
  type: "verify_passed";
  hook_id: string;
  duration_ms: number;
  output_preview?: string | null;
}
export interface VerifyFailed {
  type: "verify_failed";
  hook_id: string;
  duration_ms: number;
  error: string;
  on_failure: OnFailureRef;
}
export interface RailTriggered {
  type: "rail_triggered";
  rail_id: string;
  policy: RailPolicy;
  firing_point: string;
  message: string;
  agent_id?: string | null;
}
/**
 * Spec §4b Layer 1 (loader) or Layer 2 (request_capability) gap event for an unresolved skill reference. M05.A added `suggested_action` + `requested_via`; severity tightened from free-string to GapSeverity enum. Defaults to severity=advisory (skill gaps are recoverable per spec §4b severity matrix — load continues without).
 */
export interface SkillMissing {
  type: "skill_missing";
  agent_id: string;
  skill_name: string;
  severity: GapSeverity;
  suggested_action: SuggestedAction;
  requested_via: GapSource;
}
/**
 * Spec §4b Layer 1 (loader) or Layer 2 (request_capability) gap event for an unresolved tool reference. M05.A added `suggested_action` + `requested_via`; severity tightened from free-string to GapSeverity enum. Tool gaps are blocking per spec §4b severity matrix — the owning agent cannot proceed.
 */
export interface ToolMissing {
  type: "tool_missing";
  agent_id: string;
  tool_name: string;
  severity: GapSeverity;
  suggested_action: SuggestedAction;
  requested_via: GapSource;
}
/**
 * Spec §4b + §5: gap event for an unresolved MCP server reference. v0.1 emits this only from Layer 2 request_capability (the v0.1 framework JSON has no MCP-server declaration field — server lifecycle is M06). M05.A authoring decision: variant + payload land now so the schema is forward-compatible with M06's loader-time emission.
 */
export interface McpMissing {
  type: "mcp_missing";
  agent_id: string;
  server_name: string;
  severity: GapSeverity;
  suggested_action: SuggestedAction;
  requested_via: GapSource;
}
/**
 * Spec §4b Layer 1 (loader) — `framework.agents[].spawns[]` references an agent id absent from `framework.agents[]`. Per spec §4b severity matrix this is a load-time block: the framework fails to load (severity=critical). Also emittable from Layer 2 request_capability when an agent asks for a sub-agent it cannot spawn.
 */
export interface AgentMissing {
  type: "agent_missing";
  agent_id: string;
  missing_agent_id: string;
  severity: GapSeverity;
  suggested_action: SuggestedAction;
  requested_via: GapSource;
}
export interface GapResolved {
  type: "gap_resolved";
  agent_id: string;
  capability: string;
  kind: string;
}
/**
 * M04.E §6a — emitted when an enabled HITL trigger evaluates. Carries the correlation id (prompt_id) the renderer round-trips back via respond_hitl, the UI variant the renderer should render, the user-facing question, and the available choices. The original M03 minimal shape (prompt + hitl_kind) is replaced; no live producers existed pre-M04.E (audit-verified).
 */
export interface HitlRequested {
  type: "hitl_requested";
  /**
   * Correlation id (UUID) tying this request to the eventual hitl_resolved / hitl_timeout. The renderer passes this back via respond_hitl(prompt_id, choice).
   */
  prompt_id: string;
  trigger: HitlTriggerRef;
  /**
   * Originating agent, when applicable (per_task / per_epic are plan-level, not agent-level).
   */
  agent_id?: string | null;
  /**
   * User-facing question. Free-text per spec §6a; framework JSON authors compose.
   */
  question: string;
  /**
   * Expected choice tokens. Empty array means free-text response. Built-in options for on_failure_threshold: [retry, skip, abort].
   */
  options: string[];
  ui_variant: HitlUiVariantRef;
  /**
   * Wall-clock deadline (unix milliseconds). Renderer may display countdown; seam fires hitl_timeout when crossed.
   */
  timeout_at_unix_ms: number;
}
/**
 * M04.E §6a — emitted when the user responds to a HITL prompt. Carries the same prompt_id as the originating hitl_requested + the chosen token (from options[]) + how long the user took.
 */
export interface HitlResolved {
  type: "hitl_resolved";
  prompt_id: string;
  /**
   * Selected token; one of the originating options[], or a free-text response when options[] was empty.
   */
  choice: string;
  duration_ms: number;
}
/**
 * M04.E §6a — emitted when a HITL prompt's timeout_at_unix_ms elapses without a hitl_resolved. The default_action_on_timeout from the framework JSON (e.g. `abort`) drives downstream FSM transitions.
 */
export interface HitlTimeout {
  type: "hitl_timeout";
  prompt_id: string;
  trigger: HitlTriggerRef;
  /**
   * Free-text action token from framework JSON (e.g. `abort`). SDK consumers route this to plan / task FSM transitions.
   */
  default_action: string;
}
/**
 * M04.E §6a — emitted when a notifier (terminal_bell / desktop / sound / plugin) successfully fires for a HITL request. Notifier failures emit notifier_failed instead.
 */
export interface NotifierDispatched {
  type: "notifier_dispatched";
  /**
   * Type of notifier that fired (terminal_bell / desktop / sound / plugin).
   */
  notifier_type: string;
  trigger: HitlTriggerRef;
  success: boolean;
}
/**
 * M04.E §6a — emitted when a notifier raises an error (e.g. desktop notification permission denied). Notifier failures are NON-FATAL: the HITL seam still resolves on user response or timeout regardless of which notifiers fired.
 */
export interface NotifierFailed {
  type: "notifier_failed";
  notifier_type: string;
  trigger: HitlTriggerRef;
  /**
   * Human-readable error text. Renderer surfaces in inspector or toast.
   */
  error: string;
}
export interface CapabilityViolation {
  type: "capability_violation";
  /**
   * Agent whose dispatch the §8.security L2a enforcer rejected.
   */
  agent_id: string;
  capability_kind: CapabilityKindRef;
  requested_action: RequestedAction;
  declared_scope: DeclaredScope;
}
export interface CapabilityGrant {
  type: "capability_grant";
  /**
   * Optional — agent whose grants this grant narrows from. Absent for framework-loader-issued root grants; present whenever an agent spawns a sub-agent and narrows a subset of its grants to the child (§8.security L2a narrowing).
   */
  parent_agent_id?: string;
  /**
   * Agent receiving the grant.
   */
  granted_to: string;
  capability_kind: CapabilityKindRef1;
  resource: GrantedResource;
  /**
   * Optional — plain-English description of the parent's broader scope. Renderer uses this in the inspector to show 'narrowed from ... to ...' attribution; absent for root grants.
   */
  narrowed_from?: string;
}
export interface BudgetWarn {
  type: "budget_warn";
  spent_usd: number;
  cap_usd: number;
  percent: number;
}
export interface BudgetDownshift {
  type: "budget_downshift";
  from_model: string;
  to_model: string;
  reason: string;
}
export interface BudgetSuspended {
  type: "budget_suspended";
  spent_usd: number;
  cap_usd: number;
}
export interface BudgetExceeded {
  type: "budget_exceeded";
  spent_usd: number;
  cap_usd: number;
}
export interface StreamText {
  type: "stream_text";
  agent_id: string;
  text: string;
}
export interface DecisionRecord {
  type: "decision_record";
  agent_id: string;
  decision: string;
  rationale: string;
  tool_used?: string | null;
}
/**
 * M05 Stage D §8.security L4 — emitted when the L4 tier gate rejects a capability request before the L1 enforcer runs. Distinct from `capability_violation` (which fires on L1 rejection). Renderer routes to a tier-violation modal in the Settings panel: "Your current tier (Novice) does not permit this action; promote to Promoted or modify the request." Carries the tier that rejected + the requested kind + a plain-English action.
 */
export interface TierViolation {
  type: "tier_violation";
  /**
   * Agent whose dispatch the §8.security L4 evaluator rejected.
   */
  agent_id: string;
  tier: TierRef;
  capability_kind: CapabilityKindRef2;
  attempted_action: TierForbiddenAction;
}
/**
 * M05 Stage D §8.security L4 — emitted on a successful tier change. `previous` is the tier before the change; `current` is the tier after. Includes a plain-English `reason`. Promotion is renderer-confirmed (Settings panel modal calls `request_tier_transition`); demotion is direct. Renderer applies the new tier to its current-tier state and surfaces a toast.
 */
export interface TierTransition {
  type: "tier_transition";
  previous: TierRef;
  current: TierRef;
  reason: TierTransitionReason;
}
export interface TokenUsage {
  type: "token_usage";
  input: number;
  output: number;
  model: string;
  cost_usd: number;
}
