// AUTO-GENERATED FILE — DO NOT EDIT
//
// Regenerate with: `cargo xtask regenerate-types`
// Source schema:   schemas/budget.v1.json
// Generated by:    json-schema-to-typescript
//
// Drift detection runs in CI via `cargo xtask regenerate-types --check`.

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Which budget scope tripped a threshold. Carried on every budget event so the renderer can attribute the alert (header bar tooltip; scope badge).
 *
 * This interface was referenced by `BudgetPolicy`'s JSON-Schema
 * via the `definition` "BudgetScope".
 */
export type BudgetScope = 'session' | 'framework' | 'global';

/**
 * Spec §2a Budget Primitive — three budget scopes (session / framework / global) that stack with tightest-cap-wins semantics; four threshold actions (warn at 50%, downshift at 75%, hitl at 90%, hard-stop at 100%); optional downshift_hook referencing a tool by name. Locked at WI-07 (2026-04-18). v0.1 ships all four actions per §0d release scope matrix.
 */
export interface BudgetPolicy {
  /**
   * Per-session USD cap. Default $5.00 applies when omitted; the framework loader fills this in at framework load time. The runtime evaluates the tightest applicable cap across all three scopes — session, framework, global — and uses that cap for threshold percentage math.
   */
  session_usd_cap?: number;
  /**
   * Per-framework USD cap. Omitted means no framework-level cap; the long-running framework total is unbounded by this scope and only session + global caps apply.
   */
  framework_usd_cap?: number;
  actions?: BudgetActions;
  downshift_hook?: DownshiftHook;
}
/**
 * Four percent thresholds keyed to the tightest applicable cap. Each action is independently configurable per scope; setting any to null disables it for that scope.
 *
 * This interface was referenced by `BudgetPolicy`'s JSON-Schema
 * via the `definition` "BudgetActions".
 */
export interface BudgetActions {
  /**
   * Threshold at which the runtime emits budget_warn + surfaces a toast notification + shifts the BudgetHeaderBar color toward amber. Default 50.
   */
  warn_at_percent?: number;
  /**
   * Threshold at which the runtime invokes downshift_hook (model-tier ladder) and emits budget_downshift. Default 75.
   */
  downshift_at_percent?: number;
  /**
   * Threshold at which the runtime triggers on_budget_threshold HITL flow and emits budget_suspended; user approval required to continue. Default 90.
   */
  hitl_at_percent?: number;
  /**
   * Threshold at which the runtime emits budget_exceeded + dispatches drone StopProcess for all session-spawned agents (immediate kill). Default 100.
   */
  hard_stop_at_percent?: number;
}
/**
 * Hook invoked at downshift_at_percent. The runtime resolves the named tool from the framework's tool registry and dispatches it with the current model + remaining budget; the tool returns the new model name. v0.1 falls back to the hardcoded opus → sonnet → haiku ladder when the named tool is absent (framework tool dispatch lands in M5/M9 generators).
 *
 * This interface was referenced by `BudgetPolicy`'s JSON-Schema
 * via the `definition` "DownshiftHook".
 */
export interface DownshiftHook {
  /**
   * Hook kind discriminator. v0.1 supports only `tool`; v1.0 may add inline script hooks.
   */
  type: 'tool';
  /**
   * Tool id from the framework's tool registry.
   */
  tool_name: string;
}
