// AUTO-GENERATED FILE — DO NOT EDIT
//
// Regenerate with: `cargo xtask regenerate-types`
// Source schema:   schemas/capability.v1.json
// Generated by:    json-schema-to-typescript
//
// Drift detection runs in CI via `cargo xtask regenerate-types --check`.

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Coarse category of access the declaration covers. Five values cover the §8.security primitive surface for v0.1: file reads (`read`), file writes (`write`), tool invocations (`exec`), network egress (`network`), and child-process spawning (`process_spawn`). Adding a kind requires a v2 schema bump + ADR.
 *
 * This interface was referenced by `CapabilityDeclaration`'s JSON-Schema
 * via the `definition` "CapabilityKind".
 */
export type CapabilityKind = "read" | "write" | "exec" | "network" | "process_spawn";
/**
 * Identifier of the resource the capability applies to — tool name, file glob pattern, network hostname, or sub-agent id depending on `kind`. Free-form per kind; the enforcer's per-kind matching logic interprets it. minLength 1 — declarations may not name empty resources.
 *
 * This interface was referenced by `CapabilityDeclaration`'s JSON-Schema
 * via the `definition` "ResourceName".
 */
export type ResourceName = string;
/**
 * How the declaration's `resource` is matched at enforcement time. Three variants with mutually-exclusive shapes — glob-pattern matching, hostname (DNS-domain) matching, and path-prefix matching. The enforcer's containment logic is per-variant; cross-variant containment (e.g., a glob scope satisfying a path request) requires the path to match the glob.
 *
 * This interface was referenced by `CapabilityDeclaration`'s JSON-Schema
 * via the `definition` "CapabilityScope".
 */
export type CapabilityScope = GlobScope | DomainScope | PathScope;
/**
 * Gitignore-syntax glob pattern matched against the requested resource at enforcement time. Recursive (`** /*.md`) patterns supported. Per gotcha #43 (typify-friendly extraction): validated inline strings inside oneOf variants are extracted to $defs with a title so typify can name the newtype.
 *
 * This interface was referenced by `CapabilityDeclaration`'s JSON-Schema
 * via the `definition` "GlobPattern".
 */
export type GlobPattern = string;
/**
 * Hostname the declaration restricts network egress to. Bare host matches exactly; leading `.` (`.example.com`) matches the host and any subdomain. Per gotcha #43 (typify-friendly extraction).
 *
 * This interface was referenced by `CapabilityDeclaration`'s JSON-Schema
 * via the `definition` "DomainPattern".
 */
export type DomainPattern = string;
/**
 * Filesystem path prefix the declaration restricts read/write access to. Exact match or prefix-with-separator: `src` matches `src` and `src/anything`, but not `src-other`. Per gotcha #43 (typify-friendly extraction).
 *
 * This interface was referenced by `CapabilityDeclaration`'s JSON-Schema
 * via the `definition` "PathPattern".
 */
export type PathPattern = string;
/**
 * Severity classifier independent of `kind`. `pure` is read-only and idempotent; `filesystem_mutate` writes to disk; `network_egress` issues outbound requests; `process_spawn` creates a child process; `irreversible` covers operations the runtime cannot undo (e.g., `git push`, external API calls with side effects). Drives HITL severity + audit-log weighting at L5.
 *
 * This interface was referenced by `CapabilityDeclaration`'s JSON-Schema
 * via the `definition` "SideEffectClass".
 */
export type SideEffectClass = "pure" | "filesystem_mutate" | "network_egress" | "process_spawn" | "irreversible";

/**
 * Spec §8.security L1 — declarative shape every tool, skill, and agent attaches to itself describing what it needs (or has been granted) to do its job. The §8.security L2a enforcer compares the calling agent's grants against the requested action's declaration at every tool dispatch + sub-agent spawn; mismatches surface as `capability_violation` events that route through the M04.E `on_capability_violation` HITL trigger. Locked at M05 Stage B. Per CLAUDE.md §14 schema-as-source-of-truth: Rust types in `crates/runtime-core/src/generated/capability.rs` + TS types in `src/types/capability.ts` regenerate from this file.
 */
export interface CapabilityDeclaration {
  kind: CapabilityKind;
  resource: ResourceName;
  scope: CapabilityScope;
  side_effect_class: SideEffectClass;
}
export interface GlobScope {
  glob: GlobPattern;
}
export interface DomainScope {
  domain: DomainPattern;
}
export interface PathScope {
  path: PathPattern;
}
