// AUTO-GENERATED FILE — DO NOT EDIT
//
// Regenerate with: `cargo xtask regenerate-types`
// Source schema:   schemas/error.v1.json
// Generated by:    json-schema-to-typescript
//
// Drift detection runs in CI via `cargo xtask regenerate-types --check`.

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Wire-format error envelope for Tauri renderer↔main IPC error responses. Mirrors the runtime-main `CmdError` enum's serde(tag = "type", rename_all = "snake_case") encoding. Used by src/lib/ipc.ts::unwrapCmdError.
 */
export type CmdError = SetupRequired | Provider | Drone | KeyStore | Internal | PathNotPermitted;
/**
 * Human-readable error message body. Non-empty per validation; not localized at v0.1.
 */
export type ErrorMessage = string;

/**
 * API key not present in OS keychain; renderer prompts user to invoke set_api_key. Unit variant — no message field.
 */
export interface SetupRequired {
  type: "setup_required";
}
/**
 * LLMProvider error (Anthropic API failure, network, parsing).
 */
export interface Provider {
  type: "provider";
  message: ErrorMessage;
}
/**
 * Drone IPC failure (subprocess died, framing error, timeout).
 */
export interface Drone {
  type: "drone";
  message: ErrorMessage;
}
/**
 * OS keychain failure. Wraps keyring crate errors.
 */
export interface KeyStore {
  type: "key_store";
  message: ErrorMessage;
}
/**
 * Catch-all for unexpected runtime errors. Should be rare.
 */
export interface Internal {
  type: "internal";
  message: ErrorMessage;
}
/**
 * A renderer-supplied filesystem path was refused because it resolves outside the dialog-registered roots (M09.5.A / TD-051). The shell confines save_framework/load_framework/import_artifact(file) before any IO; this variant is the typed refusal the renderer renders.
 */
export interface PathNotPermitted {
  type: "path_not_permitted";
  message: ErrorMessage;
}
