// AUTO-GENERATED FILE — DO NOT EDIT
//
// Regenerate with: `cargo xtask regenerate-types`
// Source schema:   schemas/framework.v1.json
// Generated by:    json-schema-to-typescript
//
// Drift detection runs in CI via `cargo xtask regenerate-types --check`.

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `Framework`'s JSON-Schema
 * via the `definition` "SizingRules".
 */
export type SizingRules = {
  /**
   * JSONLogic expression. Validated structurally at parse time; operator semantics enforced at evaluation time. Operators in v0.1: var, ==, !=, <, <=, >, >=, and, or, not, in, +, -, *, /.
   */
  if?:
    | {
        [k: string]: unknown;
      }
    | boolean
    | number
    | string;
  then?: string;
  default?: string;
  [k: string]: unknown;
}[];
/**
 * This interface was referenced by `Framework`'s JSON-Schema
 * via the `definition` "LoopPolicy".
 */
export type LoopPolicy =
  | {
      kind: "one_shot";
      [k: string]: unknown;
    }
  | {
      kind: "fresh_context_per_task";
      [k: string]: unknown;
    }
  | {
      kind: "continuous";
      /**
       * Path to PRD-style goal store file.
       */
      goal_store: string;
      [k: string]: unknown;
    };
/**
 * List of glob patterns. Patterns follow gitignore syntax: leading '!' negates, trailing '/' matches directories. Symlink-escape attempts are blocked at L2 enforcement.
 */
export type FileGlobList = string[];

/**
 * Top-level framework.json schema per spec §6 (Phase 6 Framework JSON Loader). Frameworks compose runtime primitives (modes, hooks, rails, plan, HITL, budget, tools, skills, agents) into a working agentic system. examples/aria/ and examples/ralph/ are the v0.1 reference frameworks.
 */
export interface Framework {
  $schema?: string;
  name: string;
  /**
   * Semantic Versioning 2.0.0 string.
   */
  version: string;
  description: string;
  author?: string;
  model: ModelRef;
  fallback_models?: ModelRef[];
  /**
   * Per spec §15d. Named secrets the recipient must provide before running this framework. Values are never embedded — only names. Example: ["ANTHROPIC_API_KEY", "GITHUB_TOKEN"]. The runtime / CLI prompts for any missing entry on first run; subsequent runs reuse keychain-stored values. Names must match the env-var-style pattern; case-sensitive.
   */
  requires_secrets?: string[];
  /**
   * Per spec §15d. Whether the framework can run on the v1.0 headless `agent-runtime-cli` (`headless_compatible`) or requires the desktop runtime's live graph / workbench / canvas (`desktop_runtime`). Default is `desktop_runtime` (safe default — explicit opt-in required for headless). The Share It module (v1.0; spec §15e) computes the correct value via static analysis at export time.
   */
  runtime_dependency_class?: "desktop_runtime" | "headless_compatible";
  /**
   * Per spec §15c. OSes the framework supports. Default is all three (assume portable). If the framework uses an OS-specific tool (e.g., a tool that shells out to `powershell.exe`), narrow to the supported subset. The CLI / desktop runtime refuses to run a framework on an unsupported OS — fail loudly, do not silently misbehave. The Share It module narrows automatically based on tool/skill inspection.
   *
   * @minItems 1
   */
  compatible_os?: ["windows" | "macos" | "linux", ...("windows" | "macos" | "linux")[]];
  /**
   * Per spec §15d. Set automatically by the Share It module at export time; not authored by hand. Surfaces `shared on YYYY-MM-DD by ...` in the recipient runtime/CLI install dialog and provides an audit trail of any rebaking decisions.
   */
  share_provenance?: {
    /**
     * ISO 8601 UTC timestamp when the bundle was emitted.
     */
    exported_at?: string;
    /**
     * Share It module identifier and SemVer (e.g., "share-it@1.0.0").
     */
    exported_by?: string;
    /**
     * The `runtime_dependency_class` value the bundle was prepared for.
     */
    for_runtime_class?: "desktop_runtime" | "headless_compatible";
    /**
     * The OS subset the bundle was prepared for.
     *
     * @minItems 1
     */
    for_os?: ["windows" | "macos" | "linux", ...("windows" | "macos" | "linux")[]];
    /**
     * Human-readable list of substitutions / narrowings the Share It module applied at export time. Empty if no rebake was needed.
     */
    rebake_changes?: string[];
  };
  modes?: {
    /**
     * @minItems 1
     */
    values: [string, ...string[]];
    default: string;
    per_mode_overrides?: {
      /**
       * Map of dotted-path -> value. Runtime walks the framework JSON and applies overrides for the active mode at session start.
       */
      [k: string]: {
        [k: string]: unknown;
      };
    };
  };
  sizing?:
    | {
        mode: "agent";
        /**
         * Agent id from agents[] that emits propose_mode.
         */
        agent: string;
        auto_confirm?: boolean;
        fallback_rules?: SizingRules;
      }
    | {
        mode: "declarative";
        rules: SizingRules;
      };
  plan_creation?: {
    agent: string;
    approval_required?: boolean;
    loop_policy?: LoopPolicy;
  };
  task_defaults?: {
    max_failures?: number;
    hitl_default?: boolean;
    post_hooks?: (
      | Hook
      | {
          $ref: string;
          [k: string]: unknown;
        }
    )[];
  };
  /**
   * Named hook definitions referenceable via { "$ref": "#/hook_defs/<name>" } from task_defaults.post_hooks or hooks.*.
   */
  hook_defs?: {
    [k: string]: Hook;
  };
  hooks?: {
    pre_task?: Hook[];
    post_task?: Hook[];
    pre_file_edit?: Hook[];
    post_file_edit?: Hook[];
    pre_commit?: Hook[];
    pre_agent_spawn?: Hook[];
    session_end?: Hook[];
  };
  rails?: {
    hard?: Rail[];
    soft?: Rail[];
  };
  dont_touch?: FileGlobList;
  hitl_policy?: HitlPolicy;
  budget?: {
    session_usd_cap?: number;
    framework_usd_cap?: number;
    actions?: {
      warn_at_percent?: number;
      downshift_at_percent?: number;
      hitl_at_percent?: number;
      hard_stop_at_percent?: number;
    };
    /**
     * Reference to an executable hook. Three variants: shell command, tool invocation, or agent spawn.
     */
    downshift_hook?:
      | {
          type: "shell";
          command: string;
          timeout_ms?: number;
          cwd?: string;
        }
      | {
          type: "tool";
          tool_name: string;
          input?: {
            [k: string]: unknown;
          };
        }
      | {
          type: "agent";
          agent_id: string;
          prompt?: string;
        };
  };
  tools: {
    name: string;
    source: "builtin" | "generated" | "external" | "registry";
    /**
     * Relative path to tool.md (when source != 'builtin' and != 'registry').
     */
    path?: string;
    /**
     * Registry coordinate (when source == 'registry').
     */
    registry_id?: string;
  }[];
  skills: {
    name: string;
    path?: string;
    source?: "local" | "external" | "registry";
    registry_id?: string;
  }[];
  /**
   * @minItems 1
   */
  agents: [
    (
      | {
          id: string;
          path: string;
        }
      | Agent
    ),
    ...(
      | {
          id: string;
          path: string;
        }
      | Agent
    )[]
  ];
  /**
   * Agent id (must be in agents[]) that the runtime spawns at session_start.
   */
  session_root_agent: string;
  commands?: {
    name: string;
    description: string;
    agent?: string;
    tool?: string;
  }[];
  session?: {
    snapshot_interval_seconds?: number;
    idle_timeout_seconds?: number;
    stall_timeout_seconds?: number;
  };
  decision_trace?: boolean;
  design_notes_required?: boolean;
  design_doc_required?: boolean;
  /**
   * Short-name to canonical-name aliases per §5a (e.g., 'extract_text' -> 'pdf-mcp__extract_text').
   */
  mcp_aliases?: {
    [k: string]: string;
  };
  /**
   * Free-form metadata; not validated. Used by examples/aria/ to map matrix rows to file locations.
   */
  examples_archetype_proof?: {
    [k: string]: unknown;
  };
}
export interface ModelRef {
  /**
   * LLM provider identifier. v0.1 ships only 'anthropic'; others are reserved.
   */
  provider: "anthropic" | "openai" | "google" | "local-ollama";
  /**
   * Provider-specific model identifier (e.g., 'claude-sonnet-4-6').
   */
  id: string;
}
export interface Hook {
  id: string;
  category: "verify" | "lint" | "build" | "test" | "custom";
  level?: "quick" | "standard" | "full";
  /**
   * Reference to an executable hook. Three variants: shell command, tool invocation, or agent spawn.
   */
  ref:
    | {
        type: "shell";
        command: string;
        timeout_ms?: number;
        cwd?: string;
      }
    | {
        type: "tool";
        tool_name: string;
        input?: {
          [k: string]: unknown;
        };
      }
    | {
        type: "agent";
        agent_id: string;
        prompt?: string;
      };
  on_failure: "block" | "warn" | "rollback";
}
/**
 * This interface was referenced by `Framework`'s JSON-Schema
 * via the `definition` "Rail".
 */
export interface Rail {
  id: string;
  /**
   * @minItems 1
   */
  fires_on: [string, ...string[]];
  /**
   * Reference to an executable hook. Three variants: shell command, tool invocation, or agent spawn.
   */
  check:
    | {
        type: "shell";
        command: string;
        timeout_ms?: number;
        cwd?: string;
      }
    | {
        type: "tool";
        tool_name: string;
        input?: {
          [k: string]: unknown;
        };
      }
    | {
        type: "agent";
        agent_id: string;
        prompt?: string;
      };
  message: string;
}
/**
 * This interface was referenced by `Framework`'s JSON-Schema
 * via the `definition` "HitlPolicy".
 */
export interface HitlPolicy {
  on_gap?: HitlTrigger;
  on_risky_tool?: {
    enabled?: boolean;
    tools?: string[];
    ui?: "panel" | "modal" | "toast";
  };
  on_dont_touch_edit?: HitlTrigger;
  on_failure_threshold?: HitlTrigger & {
    threshold?: number;
    [k: string]: unknown;
  };
  on_capability_violation?: HitlTrigger;
  on_budget_threshold?: HitlTrigger & {
    percent?: number;
    [k: string]: unknown;
  };
  on_plan_approval?: HitlTrigger;
  per_task?: HitlTrigger;
  per_epic?: HitlTrigger;
  notifiers?: {
    type: string;
    enabled?: boolean;
    name?: string;
    config?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  timeout_seconds?: number;
  default_action_on_timeout?: "abort" | "approve" | "reject";
}
/**
 * This interface was referenced by `Framework`'s JSON-Schema
 * via the `definition` "HitlTrigger".
 */
export interface HitlTrigger {
  enabled?: boolean;
  ui?: "panel" | "modal" | "toast";
  [k: string]: unknown;
}
/**
 * Canonical agent.md frontmatter or framework.json agents[] entry per spec §0b. Agents are composable LLM roles: system prompt + allowed tools + allowed skills + model. Spawned via SpawnAgent. Capability narrowing enforced (child cannot exceed parent's allowed_* sets).
 */
export interface Agent {
  id: string;
  role: string;
  model: ModelRef;
  /**
   * Optional. If absent, runtime uses agent.md body as the prompt template. Template variables: ${session.mode}, ${task.title}, etc.
   */
  system_prompt_template?: string;
  allowed_tools: string[];
  allowed_skills: string[];
  /**
   * Agent IDs this agent may spawn. Must be a subset of capabilities.spawn_agents.
   */
  spawns: string[];
  spawn_constraints?: {
    max_concurrent?: number;
    /**
     * 0 = session lifetime (e.g., orchestrator).
     */
    timeout_ms?: number;
  };
  capabilities: Capabilities;
  provenance?: Provenance;
}
export interface Capabilities {
  /**
   * Names of tools this artifact may invoke.
   */
  tools_called: string[];
  /**
   * Names of skills this artifact may load via LoadSkill.
   */
  skills_loaded: string[];
  file_access: {
    read: FileGlobList;
    write: FileGlobList;
  };
  /**
   * Allowed hosts (HTTPS only at L2). Use '*' for unrestricted; '*' requires Operator tier per Phase 8 §8.security L4.
   */
  network: string[];
  /**
   * If true, artifact may invoke shell commands. Requires Promoted or Operator tier; sandboxed by §8.security L2b.
   */
  shell: boolean;
  /**
   * Agent IDs this artifact may spawn via SpawnAgent. Capability narrowing enforced (child cannot exceed parent).
   */
  spawn_agents: string[];
}
export interface Provenance {
  /**
   * How this artifact came into existence. 'hand-authored' artifacts default to Operator-tier-only loading per §8.security L4.
   */
  generator: "hand-authored" | "tool_writer" | "skill_writer" | "agent_composer" | "imported";
  /**
   * Free-form source description (e.g., '.aria/skills/planning.md (ported)' or registry URL).
   */
  source?: string;
  /**
   * LLM model used for generation, if generated.
   */
  model?: string;
  /**
   * SHA-256 of the generation prompt; full prompt stored in skills.audit.jsonl.
   */
  prompt_hash?: string;
  generated_at?: string;
  validated_at?: string;
  authored_at?: string;
  validation_report_id?: string;
  /**
   * SHA-256 of post-validation artifact content. Placeholder allowed during authoring; replaced on install.
   */
  content_hash?: string;
  /**
   * ed25519 or sigstore signature; runtime-signed at install.
   */
  signature?: string;
}
