// AUTO-GENERATED FILE — DO NOT EDIT
//
// Regenerate with: `cargo xtask regenerate-types`
// Source schema:   schemas/mcp.v1.json
// Generated by:    json-schema-to-typescript
//
// Drift detection runs in CI via `cargo xtask regenerate-types --check`.

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Server identifier — lowercase alphanumeric + hyphen, 1–64 chars. Used as the namespace prefix in §5a tool resolution (`<server>__<tool>`). Pattern matches DNS-label conventions; first character must be alphanumeric (no leading hyphens).
 *
 * This interface was referenced by `McpServerConfig`'s JSON-Schema
 * via the `definition` "McpServerName".
 */
export type McpServerName = string;
/**
 * Transport variant — stdio (local subprocess via JSON-RPC over stdin/stdout, suitable for `@modelcontextprotocol/server-filesystem` and similar local servers) or http (remote streamable HTTP per MCP specification 2025-11-25). Discriminated by the `type` field per gotcha #26 (struct-shape variants required for serde(tag)).
 *
 * This interface was referenced by `McpServerConfig`'s JSON-Schema
 * via the `definition` "McpTransport".
 */
export type McpTransport = StdioTransportConfig | HttpTransportConfig;
/**
 * OS-keychain key identifier for per-server authentication secrets; null for unauthenticated servers. Stage C wires the per-server keychain surface via `runtime-main::key_store`. The string format is `mcp.<server-name>` by convention; the runtime owns the namespace, the schema is permissive (any non-empty string).
 */
export type AuthSecretRef = string | null;
/**
 * Runtime status of an MCP server connection. Surfaced by §5 lifecycle (Stage C) and rendered by the MCPNode (Stage E). Transitions: `disconnected → health_pending → connected` on add; `connected → error` on transport failure; `error → health_pending → connected` on auto-reconnect.
 *
 * This interface was referenced by `McpServerConfig`'s JSON-Schema
 * via the `definition` "McpServerStatus".
 */
export type McpServerStatus = "connected" | "disconnected" | "health_pending" | "error";

/**
 * MCP server configuration (spec §5). One MCP server's identity + transport + optional per-server auth-secret reference. Two transport variants — stdio (local subprocess JSON-RPC over stdin/stdout) and http (remote streamable HTTP per MCP specification 2025-11-25). Stage C lifecycle holds one config per registered server in the `mcp_servers` SQLite table. Per CLAUDE.md §14 schema-as-source-of-truth: Rust types in `crates/runtime-core/src/generated/mcp.rs` + TS types in `src/types/mcp.ts` regenerate from this file.
 */
export interface McpServerConfig {
  name: McpServerName;
  transport: McpTransport;
  auth_secret_ref?: AuthSecretRef;
}
export interface StdioTransportConfig {
  type: "stdio";
  /**
   * Executable name (PATH-resolved) or absolute path.
   */
  command: string;
  /**
   * Command-line arguments passed after the executable name.
   */
  args?: string[];
  /**
   * Environment variables set for the subprocess. Inherits from parent unless an env key is explicitly overridden here.
   */
  env?: {
    [k: string]: string;
  };
  /**
   * Working directory for the subprocess. null = inherit from parent.
   */
  cwd?: string | null;
}
export interface HttpTransportConfig {
  type: "http";
  /**
   * Streamable-HTTP endpoint URL (per MCP specification 2025-11-25). HTTPS endpoints use rustls TLS (configured via the workspace reqwest pin).
   */
  url: string;
}
