// AUTO-GENERATED FILE — DO NOT EDIT
//
// Regenerate with: `cargo xtask regenerate-types`
// Source schema:   schemas/plan.v1.json
// Generated by:    json-schema-to-typescript
//
// Drift detection runs in CI via `cargo xtask regenerate-types --check`.

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Human-readable plan title. Non-empty per validation; not localized at v0.1.
 *
 * This interface was referenced by `Plan`'s JSON-Schema
 * via the `definition` "PlanTitle".
 */
export type PlanTitle = string;
/**
 * Plan FSM state per spec §3a. Transitions enforced by `runtime_main::plan::state_machine::PlanStateMachine`.
 *
 * This interface was referenced by `Plan`'s JSON-Schema
 * via the `definition` "PlanStatus".
 */
export type PlanStatus = "pending_approval" | "approved" | "in_progress" | "awaiting_replan" | "complete" | "aborted";
/**
 * Loop policy for task execution. v0.1 hardcodes `fresh_context_per_task`; the other two variants exist as spec-prep and the SDK's loop-policy seam returns `LoopPolicyError::NotImplemented` for them.
 *
 * This interface was referenced by `Plan`'s JSON-Schema
 * via the `definition` "LoopPolicy".
 */
export type LoopPolicy = "one_shot" | "fresh_context_per_task" | "continuous";

/**
 * Plan primitive — orchestrator-emitted multi-task work unit. Spec §3a (Data types) + spec §10 (plans table DDL). The renderer's PlanNode + projector's plans table both consume this shape. v0.1 hardcodes `loop_policy = fresh_context_per_task` (one_shot + continuous are spec-prep enum variants only).
 */
export interface Plan {
  /**
   * Plan UUID.
   */
  id: string;
  /**
   * Owning session UUID.
   */
  session_id: string;
  title: PlanTitle;
  /**
   * Free-text plan description.
   */
  description?: string | null;
  status: PlanStatus;
  /**
   * When true, plan suspends on `plan_approval_requested` until the approval seam resolves.
   */
  approval_required: boolean;
  loop_policy: LoopPolicy;
  /**
   * Task IDs at which HITL checkpoints fire. Stage E wires the trigger flow.
   */
  hitl_checkpoints: string[];
  /**
   * Free-text risk callouts. Surfaced in the Stage C ApprovalPanel.
   */
  risks: string[];
  /**
   * Agent ID that created the plan, or `'user'` for user-authored plans.
   */
  created_by?: string | null;
  /**
   * Unix milliseconds.
   */
  created_at: number;
  approved_at?: number | null;
  completed_at?: number | null;
}
