// AUTO-GENERATED FILE — DO NOT EDIT
//
// Regenerate with: `cargo xtask regenerate-types`
// Source schema:   schemas/task.v1.json
// Generated by:    json-schema-to-typescript
//
// Drift detection runs in CI via `cargo xtask regenerate-types --check`.

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Human-readable task title. Non-empty per validation.
 *
 * This interface was referenced by `Task`'s JSON-Schema
 * via the `definition` "TaskTitle".
 */
export type TaskTitle = string;
/**
 * Task FSM state per spec §3a. Transitions enforced by `runtime_main::plan::state_machine::TaskStateMachine`. Recovery sets currently-running tasks to `pending` (NOT `running`) per spec §1b.
 *
 * This interface was referenced by `Task`'s JSON-Schema
 * via the `definition` "TaskStatus".
 */
export type TaskStatus = "pending" | "running" | "done" | "failed" | "blocked" | "skipped" | "escalated";

/**
 * Task primitive — child of a Plan. Spec §3a (Data types) + spec §10 (tasks table DDL). The renderer's TaskNode + projector's tasks table both consume this shape. Failure escalation: when `failure_count >= max_failures`, the SDK emits `task_escalated` (Stage E routes to HITL).
 */
export interface Task {
  /**
   * Task UUID.
   */
  id: string;
  /**
   * Owning Plan UUID.
   */
  plan_id: string;
  title: TaskTitle;
  status: TaskStatus;
  /**
   * Whether this task is a HITL checkpoint.
   */
  hitl: boolean;
  /**
   * Reason surfaced in the HITL panel (Stage E).
   */
  hitl_reason?: string | null;
  /**
   * Number of failed attempts; resets to 0 on retry success.
   */
  failure_count: number;
  /**
   * Default 3 per spec §3a. Beyond this, the FSM transitions to `escalated`.
   */
  max_failures: number;
  /**
   * Glob patterns the task expects to modify. Stage D rails check this.
   */
  files_affected?: string[] | null;
  /**
   * Free-text acceptance criteria. Optional; pure documentation at v0.1.
   */
  acceptance_criteria?: string[] | null;
  created_at: number;
  started_at?: number | null;
  completed_at?: number | null;
  estimated_minutes?: number | null;
  actual_minutes?: number | null;
}
