//! `AgentEvent` — canonical event union emitted by the runtime.
//!
//! Variants span the spec sections they belong to; cross-references in
//! variant doc comments link back to the originating spec section.
//!
//! Variants that aren't yet emitted at v0.1 are still defined here so later
//! milestones extend the union additively (semver-minor, no breaking change).

use serde::{Deserialize, Serialize};

/// Origin of a tool invocation. Spec §0b + §2.
///
/// `Builtin` is the v0.1 default for tools the runtime ships natively. `Mcp`
/// indicates a tool reached via an MCP server (M06). `Generated` covers tools
/// emitted by the workbench generators (M08+).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ToolSource {
    /// Runtime-native built-in tool.
    Builtin,
    /// Tool served by an MCP server.
    Mcp,
    /// Tool generated by the workbench.
    Generated,
}

/// Source of a `PlanApproved` event. Spec §3a (approval gate primitive).
///
/// `User` indicates the renderer's HITL approval seam resolved the gate.
/// `Auto` indicates the framework JSON declared `approval_required: false`
/// — the SDK auto-approves immediately after `plan_created` without ever
/// emitting `plan_approval_requested`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ApprovedBy {
    /// HITL approval via the renderer.
    User,
    /// Framework-declared auto-approval (no HITL).
    Auto,
}

/// The canonical event union emitted by the runtime across all phases.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AgentEvent {
    // ── Session lifecycle (spec §2) ──
    /// A new session has started.
    SessionStart {
        /// Unique session identifier.
        session_id: String,
        /// Framework name/path.
        framework: String,
        /// LLM model identifier.
        model: String,
    },
    /// A session has ended.
    SessionEnd {
        /// The session that ended.
        session_id: String,
        /// Total session duration in milliseconds.
        duration_ms: u64,
        /// Why the session ended.
        end_reason: String,
    },

    // ── Agent lifecycle (spec §2) ──
    /// An agent was spawned.
    AgentSpawned {
        /// Unique agent identifier.
        agent_id: String,
        /// Agent name from the framework.
        agent_name: String,
        /// Parent agent id, if this is a child agent.
        parent_id: Option<String>,
        /// The session this agent belongs to.
        session_id: String,
    },
    /// An agent completed successfully.
    AgentComplete {
        /// The agent that completed.
        agent_id: String,
        /// Result summary.
        result: String,
        /// Total tokens (input + output) consumed by the agent across
        /// the session, when the provider surfaces it (Anthropic
        /// `message_delta.usage`). `None` when no token data is
        /// available; never confused with a real zero.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        tokens_total: Option<u64>,
    },
    /// An agent encountered an error.
    AgentError {
        /// The agent that errored.
        agent_id: String,
        /// Error description.
        error: String,
    },

    // ── Tool / Skill (spec §0b + §2) ──
    /// A tool was invoked by an agent.
    ToolInvoked {
        /// The invoking agent.
        agent_id: String,
        /// Tool name.
        tool_name: String,
        /// Tool source (built-in, MCP, generated). M02 defaults to `Builtin`;
        /// M06 refines based on the tool registry.
        source: ToolSource,
        /// MCP server name when [`ToolSource::Mcp`]; otherwise `None`.
        server: Option<String>,
        /// Tool input payload.
        input: serde_json::Value,
    },
    /// A tool returned a result.
    ToolResult {
        /// The invoking agent.
        agent_id: String,
        /// Tool name.
        tool_name: String,
        /// Tool output payload.
        output: serde_json::Value,
        /// Execution time in milliseconds.
        duration_ms: u64,
        /// Input tokens charged for this tool call, when the provider
        /// surfaces per-call attribution. `None` when no token data is
        /// available; Anthropic does not surface per-tool counts at the
        /// SSE level, so production paths leave this as `None` for now.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        tokens_in: Option<u64>,
        /// Output tokens charged for this tool call. Same caveat as
        /// `tokens_in`.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        tokens_out: Option<u64>,
    },
    /// A tool call errored.
    ToolError {
        /// The invoking agent.
        agent_id: String,
        /// Tool name.
        tool_name: String,
        /// Error description.
        error: String,
    },
    /// A skill was loaded into an agent's context.
    SkillLoaded {
        /// The agent that loaded the skill.
        agent_id: String,
        /// Skill name.
        skill_name: String,
        /// Mode variant used for filtering, if any.
        mode: Option<String>,
    },

    // ── Plan / Task lifecycle (spec §3a) ──
    /// A plan was created. M04 Stage B reconciled to spec §3a shape:
    /// adds `title` + `approval_required`. The `task_*.plan_id`
    /// denormalization is kept (drift carve-out) so downstream consumers
    /// (renderer, projector, replay) stay self-contained.
    PlanCreated {
        /// Unique plan identifier.
        plan_id: String,
        /// Human-readable plan title.
        title: String,
        /// Number of tasks in the plan.
        task_count: u32,
        /// When true, plan suspends on `plan_approval_requested` until the
        /// approval seam resolves. When false, the SDK auto-emits
        /// `plan_approved { approved_by: 'auto' }` directly.
        approval_required: bool,
    },
    /// A plan is awaiting human approval. SDK emits this immediately after
    /// `plan_created` when `approval_required = true`; the SDK then
    /// suspends on `ApprovalSeam::await_approval` until the renderer
    /// resolves it.
    PlanApprovalRequested {
        /// The plan awaiting approval.
        plan_id: String,
    },
    /// A plan was approved. M04 Stage B reconciled to spec §3a shape:
    /// adds `approved_by` (`user` for HITL approval, `auto` when
    /// `approval_required: false`).
    PlanApproved {
        /// The approved plan.
        plan_id: String,
        /// Source of the approval.
        approved_by: ApprovedBy,
    },
    /// A plan was revised. Emitted when the user requests changes via the
    /// approval seam; the SDK regenerates the plan and re-emits
    /// `plan_approval_requested`.
    PlanRevised {
        /// The revised plan.
        plan_id: String,
        /// Why the plan was revised (free-text, surfaced in the panel).
        revision_reason: String,
    },
    /// A plan was aborted. Replaces the M03 `plan_rejected` variant per
    /// spec §3a unification (the renderer treats "user said no" the same
    /// regardless of whether it was at approval-time or mid-execution).
    PlanAborted {
        /// The aborted plan.
        plan_id: String,
        /// Free-text reason.
        reason: String,
    },
    /// A plan completed (all tasks reached terminal-non-failed).
    PlanComplete {
        /// The completed plan.
        plan_id: String,
        /// End-to-end plan duration in milliseconds.
        duration_ms: u64,
    },
    /// A task within a plan started executing.
    TaskStarted {
        /// The parent plan (denormalization drift carve-out).
        plan_id: String,
        /// The task that started.
        task_id: String,
        /// The agent executing the task.
        agent_id: String,
    },
    /// A task within a plan completed.
    TaskCompleted {
        /// The parent plan (denormalization drift carve-out).
        plan_id: String,
        /// The completed task.
        task_id: String,
        /// Task execution time in milliseconds.
        duration_ms: u64,
    },
    /// A task within a plan failed.
    TaskFailed {
        /// The parent plan (denormalization drift carve-out).
        plan_id: String,
        /// The failed task.
        task_id: String,
        /// Error description.
        error: String,
        /// How many times this task has failed.
        failure_count: u32,
    },
    /// A task was skipped (e.g., HITL chose to skip after escalation, or
    /// preconditions weren't met).
    TaskSkipped {
        /// The parent plan (denormalization drift carve-out).
        plan_id: String,
        /// The skipped task.
        task_id: String,
        /// Free-text reason.
        reason: String,
    },
    /// A task was rolled back to a prior snapshot. M04 Stage B keeps this
    /// as a typed event with `snapshot_id` (drift carve-out vs spec §4a's
    /// stringly-typed error pattern; CLAUDE.md §9 anti-pattern).
    TaskRolledBack {
        /// The parent plan (denormalization drift carve-out).
        plan_id: String,
        /// The rolled-back task.
        task_id: String,
        /// Snapshot used for rollback.
        snapshot_id: String,
    },
    /// A task was escalated (e.g., to a human). M04 Stage B reconciled to
    /// spec §3a shape: replaces `reason` with `failure_count` +
    /// `max_failures` (the FSM emits this once `failure_count >=
    /// max_failures`).
    TaskEscalated {
        /// The parent plan (denormalization drift carve-out).
        plan_id: String,
        /// The escalated task.
        task_id: String,
        /// How many failures triggered escalation.
        failure_count: u32,
        /// Failure budget the task exceeded.
        max_failures: u32,
    },

    // ── Mode (spec §3b) ──
    /// The active mode changed.
    ModeChanged {
        /// Previous mode.
        from: String,
        /// New mode.
        to: String,
        /// Reason for the change.
        reason: String,
    },

    // ── Verify + Rails (spec §4a) ──
    /// A verification hook started.
    VerifyStarted {
        /// Hook identifier.
        hook_id: String,
        /// Verification level.
        level: String,
    },
    /// A verification hook passed.
    VerifyPassed {
        /// Hook identifier.
        hook_id: String,
        /// Verification duration in milliseconds.
        duration_ms: u64,
    },
    /// A verification hook failed.
    VerifyFailed {
        /// Hook identifier.
        hook_id: String,
        /// Error description.
        error: String,
    },
    /// A rail was triggered.
    RailTriggered {
        /// Rail identifier.
        rail_id: String,
        /// Severity level.
        severity: String,
        /// Human-readable message.
        message: String,
    },

    // ── Gap detection (spec §4b) ──
    /// A required skill is missing.
    SkillMissing {
        /// The agent that needs the skill.
        agent_id: String,
        /// Name of the missing skill.
        skill_name: String,
        /// Severity of the gap.
        severity: String,
    },
    /// A required tool is missing.
    ToolMissing {
        /// The agent that needs the tool.
        agent_id: String,
        /// Name of the missing tool.
        tool_name: String,
        /// Severity of the gap.
        severity: String,
    },
    /// A previously detected gap was resolved.
    GapResolved {
        /// The agent whose gap was resolved.
        agent_id: String,
        /// The capability that was provided.
        capability: String,
        /// Kind of capability (tool or skill).
        kind: String,
    },

    // ── HITL (spec §6a) ──
    /// A human-in-the-loop interaction was requested.
    HitlRequested {
        /// The requesting agent.
        agent_id: String,
        /// The prompt shown to the human.
        prompt: String,
        /// Kind of HITL interaction.
        hitl_kind: String,
    },
    /// A human-in-the-loop interaction was resolved.
    HitlResolved {
        /// The requesting agent.
        agent_id: String,
        /// The human's response.
        response: String,
        /// Time the human took to respond in milliseconds.
        duration_ms: u64,
    },

    // ── Capability enforcement (spec §8.security) ──
    /// An agent attempted an action outside its declared capabilities.
    CapabilityViolation {
        /// The violating agent.
        agent_id: String,
        /// What was declared.
        declared: String,
        /// What was attempted.
        attempted: String,
    },
    /// A capability was granted to an agent.
    CapabilityGrant {
        /// The agent receiving the grant.
        agent_id: String,
        /// The granted capability.
        capability: String,
        /// Scope of the grant.
        scope: String,
    },

    // ── Budget (spec §2a) ──
    /// Budget warning threshold reached.
    BudgetWarn {
        /// Amount spent so far in USD.
        spent_usd: f64,
        /// Budget cap in USD.
        cap_usd: f64,
        /// Percentage of budget used.
        percent: u32,
    },
    /// Budget triggered a model downshift.
    BudgetDownshift {
        /// Model being downshifted from.
        from_model: String,
        /// Model being downshifted to.
        to_model: String,
        /// Reason for the downshift.
        reason: String,
    },
    /// Session suspended due to budget.
    BudgetSuspended {
        /// Amount spent so far in USD.
        spent_usd: f64,
        /// Budget cap in USD.
        cap_usd: f64,
    },
    /// Budget exceeded.
    BudgetExceeded {
        /// Amount spent so far in USD.
        spent_usd: f64,
        /// Budget cap in USD.
        cap_usd: f64,
    },

    // ── Stream + decision trace (spec §2 + §2b) ──
    /// Streaming text from an agent.
    StreamText {
        /// The streaming agent.
        agent_id: String,
        /// The text chunk.
        text: String,
    },
    /// A decision was recorded in the VDR.
    DecisionRecord {
        /// The agent that made the decision.
        agent_id: String,
        /// What was decided.
        decision: String,
        /// Why it was decided.
        rationale: String,
        /// Tool used, if any.
        tool_used: Option<String>,
    },
    /// Token usage report.
    TokenUsage {
        /// Input tokens consumed.
        input: u64,
        /// Output tokens produced.
        output: u64,
        /// Model used.
        model: String,
        /// Estimated cost in USD.
        cost_usd: f64,
    },
}

#[cfg(test)]
mod proptest_round_trip {
    use super::*;
    use proptest::prelude::*;

    fn arb_session_start() -> impl Strategy<Value = AgentEvent> {
        (any::<String>(), any::<String>(), any::<String>()).prop_map(
            |(session_id, framework, model)| AgentEvent::SessionStart {
                session_id,
                framework,
                model,
            },
        )
    }

    fn arb_tool_source() -> impl Strategy<Value = ToolSource> {
        prop_oneof![
            Just(ToolSource::Builtin),
            Just(ToolSource::Mcp),
            Just(ToolSource::Generated),
        ]
    }

    fn arb_tool_invoked() -> impl Strategy<Value = AgentEvent> {
        (
            any::<String>(),
            any::<String>(),
            arb_tool_source(),
            proptest::option::of(any::<String>()),
        )
            .prop_map(
                |(agent_id, tool_name, source, server)| AgentEvent::ToolInvoked {
                    agent_id,
                    tool_name,
                    source,
                    server,
                    input: serde_json::json!({"key": "value"}),
                },
            )
    }

    fn arb_agent_spawned() -> impl Strategy<Value = AgentEvent> {
        (
            any::<String>(),
            any::<String>(),
            proptest::option::of(any::<String>()),
            any::<String>(),
        )
            .prop_map(|(agent_id, agent_name, parent_id, session_id)| {
                AgentEvent::AgentSpawned {
                    agent_id,
                    agent_name,
                    parent_id,
                    session_id,
                }
            })
    }

    proptest! {
        #[test]
        fn session_start_round_trips(event in arb_session_start()) {
            let json: serde_json::Value = serde_json::to_value(&event).unwrap();
            let back: AgentEvent = serde_json::from_value(json).unwrap();
            prop_assert_eq!(event, back);
        }

        #[test]
        fn tool_invoked_round_trips(event in arb_tool_invoked()) {
            let json: serde_json::Value = serde_json::to_value(&event).unwrap();
            let back: AgentEvent = serde_json::from_value(json).unwrap();
            prop_assert_eq!(event, back);
        }

        #[test]
        fn agent_spawned_round_trips(event in arb_agent_spawned()) {
            let json: serde_json::Value = serde_json::to_value(&event).unwrap();
            let back: AgentEvent = serde_json::from_value(json).unwrap();
            prop_assert_eq!(event, back);
        }

        // Newline-delimited JSON codec round trip — the wire format used by
        // the SSE event pipeline (`tokio_util::codec::LinesCodec`).
        #[test]
        fn agent_event_codec_round_trip_proptest(event in arb_session_start()) {
            let line = serde_json::to_string(&event).unwrap();
            prop_assert!(!line.contains('\n'));
            let back: AgentEvent = serde_json::from_str(&line).unwrap();
            prop_assert_eq!(event, back);
        }
    }
}
