//! `AgentEvent` — canonical event union emitted by the runtime.
//!
//! Variants span the spec sections they belong to; cross-references in
//! variant doc comments link back to the originating spec section.
//!
//! Variants that aren't yet emitted at v0.1 are still defined here so later
//! milestones extend the union additively (semver-minor, no breaking change).

use serde::{Deserialize, Serialize};

/// Origin of a tool invocation. Spec §0b + §2.
///
/// `Builtin` is the v0.1 default for tools the runtime ships natively. `Mcp`
/// indicates a tool reached via an MCP server (M06). `Generated` covers tools
/// emitted by the workbench generators (M08+).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ToolSource {
    /// Runtime-native built-in tool.
    Builtin,
    /// Tool served by an MCP server.
    Mcp,
    /// Tool generated by the workbench.
    Generated,
}

/// Source of a `PlanApproved` event. Spec §3a (approval gate primitive).
///
/// `User` indicates the renderer's HITL approval seam resolved the gate.
/// `Auto` indicates the framework JSON declared `approval_required: false`
/// — the SDK auto-approves immediately after `plan_created` without ever
/// emitting `plan_approval_requested`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ApprovedBy {
    /// HITL approval via the renderer.
    User,
    /// Framework-declared auto-approval (no HITL).
    Auto,
}

/// HITL trigger discriminator. Spec §6a (9 values, locked).
///
/// Embedded in HITL + notifier events. Mirrors
/// `runtime_core::generated::hitl::HitlTrigger`; duplicated here because
/// typify does not cross-schema-`$ref` enums and the hand-curated
/// `event.rs` keeps the renderer's union flat.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HitlTriggerRef {
    /// Gap detected (missing tool / skill) — §4b.
    OnGap,
    /// Agent attempted a tool in the `tools` allowlist of the trigger.
    OnRiskyTool,
    /// Agent attempted to edit a `dont_touch` path — §4a.
    OnDontTouchEdit,
    /// Task escalated after `failure_count >= max_failures` — §3a.
    OnFailureThreshold,
    /// Capability violation — §8.security L2 (M5 source).
    OnCapabilityViolation,
    /// Budget percent threshold crossed — §2a (M04 Stage F source).
    OnBudgetThreshold,
    /// Plan approval gate — §3a (Stage C already wired via `ApprovalSeam`).
    OnPlanApproval,
    /// HITL gate before each task.
    PerTask,
    /// HITL gate at plan / epic boundaries.
    PerEpic,
}

/// HITL UI variant discriminator embedded in `HitlRequested` events. Spec §6a.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HitlUiVariantRef {
    /// Full-takeover panel; graph stays queryable (ARIA non-modal).
    Panel,
    /// Floating modal dialog; blocks adjacent interaction (ARIA modal).
    Modal,
    /// Non-blocking auto-dismiss notification (`role=status`).
    Toast,
}

/// Severity matrix for gap events — spec §4b (M05 Stage A).
///
/// Drives session-state transitions:
/// - `Critical` blocks the session (loader-detected tool / agent gaps).
/// - `Important` blocks the owning agent but lets the session continue.
/// - `Advisory` warns and continues (skill gaps).
/// - `Requested` marks `request_capability`-emitted gaps so the renderer
///   distinguishes loader vs meta-tool origin within the same tier.
///
/// Mirrors `runtime_core::generated::event::GapSeverity`; hand-rolled here
/// because typify cross-schema `$ref` is unsupported, matching the
/// [`HitlTriggerRef`] / `HookCategoryRef` precedent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GapSeverityRef {
    /// Blocks the session.
    Critical,
    /// Blocks the owning agent; session continues.
    Important,
    /// Warning; load / agent continues without the missing primitive.
    Advisory,
    /// `request_capability`-emitted marker — severity is set by the HITL
    /// resolution flow rather than predetermined.
    Requested,
}

/// How a gap was discovered — spec §4b (M05 Stage A).
///
/// `Loader` = `framework_loader` walked the framework JSON at session start
/// and the reference did not resolve. `RequestCapability` = a running agent
/// asked for the capability mid-session via the meta-tool. Drives renderer
/// display + HITL prompt copy.
///
/// Mirrors `runtime_core::generated::event::GapSource`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GapSourceRef {
    /// Discovered at framework-load time by the loader walker.
    Loader,
    /// Requested mid-session by an agent via the meta-tool.
    RequestCapability,
}

/// Capability-kind discriminator embedded in `CapabilityViolation` +
/// `CapabilityGrant` events — spec §8.security L1 (M05 Stage B).
///
/// Mirrors `runtime_core::generated::capability::CapabilityKind` and the
/// `CapabilityKindRef` enum in `event.v1.json` `$defs`. Five values
/// covering the v0.1 enforcer surface; adding a kind requires a v2
/// schema bump + ADR per the schema-versioning policy. Hand-rolled here
/// because typify cross-schema `$ref` is unsupported, matching the
/// [`HitlTriggerRef`] / [`GapSeverityRef`] / [`GapSourceRef`] precedent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CapabilityKindRef {
    /// Read access to a file path / glob.
    Read,
    /// Write access to a file path / glob.
    Write,
    /// Invocation of a tool by name.
    Exec,
    /// Network egress to a hostname / domain.
    Network,
    /// Spawning a child process.
    ProcessSpawn,
}

/// User tier discriminator embedded in `TierViolation` + `TierTransition`
/// events — spec §8.security L4 (M05 Stage D).
///
/// Mirrors `runtime_core::generated::event::TierRef` and the `TierRef`
/// enum in `event.v1.json` `$defs`. Two values for v0.1 per §0d release
/// scope; Full tier post-v0.1 would require a v2 schema bump + ADR.
/// Hand-rolled here because typify cross-schema `$ref` is unsupported,
/// matching the [`HitlTriggerRef`] / [`CapabilityKindRef`] precedent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TierRef {
    /// Default-safe tier — curated allowlist (read + HTTPS-only network).
    Novice,
    /// Full capability surface — L1 still narrows by declaration.
    Promoted,
}

/// The canonical event union emitted by the runtime across all phases.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AgentEvent {
    // ── Session lifecycle (spec §2) ──
    /// A new session has started.
    SessionStart {
        /// Unique session identifier.
        session_id: String,
        /// Framework name/path.
        framework: String,
        /// LLM model identifier.
        model: String,
    },
    /// A session has ended.
    SessionEnd {
        /// The session that ended.
        session_id: String,
        /// Total session duration in milliseconds.
        duration_ms: u64,
        /// Why the session ended.
        end_reason: String,
    },

    // ── Agent lifecycle (spec §2) ──
    /// An agent was spawned.
    AgentSpawned {
        /// Unique agent identifier.
        agent_id: String,
        /// Agent name from the framework.
        agent_name: String,
        /// Parent agent id, if this is a child agent.
        parent_id: Option<String>,
        /// The session this agent belongs to.
        session_id: String,
        /// Optional pre-narrow proposed grants when this spawn flowed
        /// through the L2a narrowing seam (M06 Stage A wire-up of the
        /// M05.B `narrow` primitive). Each entry is one short
        /// `kind:resource:scope:side_effect_class` description of a
        /// proposed child capability. Empty / absent for top-level
        /// agents (no parent grants to narrow against) or for spawns
        /// that pre-date the wire-up (e.g., M02 smoke session).
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        narrowed_from: Vec<String>,
    },
    /// An agent completed successfully.
    AgentComplete {
        /// The agent that completed.
        agent_id: String,
        /// Result summary.
        result: String,
        /// Total tokens (input + output) consumed by the agent across
        /// the session, when the provider surfaces it (Anthropic
        /// `message_delta.usage`). `None` when no token data is
        /// available; never confused with a real zero.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        tokens_total: Option<u64>,
    },
    /// An agent encountered an error.
    AgentError {
        /// The agent that errored.
        agent_id: String,
        /// Error description.
        error: String,
    },

    // ── Tool / Skill (spec §0b + §2) ──
    /// A tool was invoked by an agent.
    ToolInvoked {
        /// The invoking agent.
        agent_id: String,
        /// Tool name.
        tool_name: String,
        /// Tool source (built-in, MCP, generated). M02 defaults to `Builtin`;
        /// M06 refines based on the tool registry.
        source: ToolSource,
        /// MCP server name when [`ToolSource::Mcp`]; otherwise `None`.
        server: Option<String>,
        /// Tool input payload.
        input: serde_json::Value,
    },
    /// A tool returned a result.
    ToolResult {
        /// The invoking agent.
        agent_id: String,
        /// Tool name.
        tool_name: String,
        /// Tool output payload.
        output: serde_json::Value,
        /// Execution time in milliseconds.
        duration_ms: u64,
        /// Input tokens charged for this tool call, when the provider
        /// surfaces per-call attribution. `None` when no token data is
        /// available; Anthropic does not surface per-tool counts at the
        /// SSE level, so production paths leave this as `None` for now.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        tokens_in: Option<u64>,
        /// Output tokens charged for this tool call. Same caveat as
        /// `tokens_in`.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        tokens_out: Option<u64>,
    },
    /// A tool call errored.
    ToolError {
        /// The invoking agent.
        agent_id: String,
        /// Tool name.
        tool_name: String,
        /// Error description.
        error: String,
    },
    /// A skill was loaded into an agent's context.
    SkillLoaded {
        /// The agent that loaded the skill.
        agent_id: String,
        /// Skill name.
        skill_name: String,
        /// Mode variant used for filtering, if any.
        mode: Option<String>,
    },

    // ── Plan / Task lifecycle (spec §3a) ──
    /// A plan was created. M04 Stage B reconciled to spec §3a shape:
    /// adds `title` + `approval_required`. The `task_*.plan_id`
    /// denormalization is kept (drift carve-out) so downstream consumers
    /// (renderer, projector, replay) stay self-contained.
    PlanCreated {
        /// Unique plan identifier.
        plan_id: String,
        /// Human-readable plan title.
        title: String,
        /// Number of tasks in the plan.
        task_count: u32,
        /// When true, plan suspends on `plan_approval_requested` until the
        /// approval seam resolves. When false, the SDK auto-emits
        /// `plan_approved { approved_by: 'auto' }` directly.
        approval_required: bool,
    },
    /// A plan is awaiting human approval. SDK emits this immediately after
    /// `plan_created` when `approval_required = true`; the SDK then
    /// suspends on `ApprovalSeam::await_approval` until the renderer
    /// resolves it.
    PlanApprovalRequested {
        /// The plan awaiting approval.
        plan_id: String,
    },
    /// A plan was approved. M04 Stage B reconciled to spec §3a shape:
    /// adds `approved_by` (`user` for HITL approval, `auto` when
    /// `approval_required: false`).
    PlanApproved {
        /// The approved plan.
        plan_id: String,
        /// Source of the approval.
        approved_by: ApprovedBy,
    },
    /// A plan was revised. Emitted when the user requests changes via the
    /// approval seam; the SDK regenerates the plan and re-emits
    /// `plan_approval_requested`.
    PlanRevised {
        /// The revised plan.
        plan_id: String,
        /// Why the plan was revised (free-text, surfaced in the panel).
        revision_reason: String,
    },
    /// A plan was aborted. Replaces the M03 `plan_rejected` variant per
    /// spec §3a unification (the renderer treats "user said no" the same
    /// regardless of whether it was at approval-time or mid-execution).
    PlanAborted {
        /// The aborted plan.
        plan_id: String,
        /// Free-text reason.
        reason: String,
    },
    /// A plan completed (all tasks reached terminal-non-failed).
    PlanComplete {
        /// The completed plan.
        plan_id: String,
        /// End-to-end plan duration in milliseconds.
        duration_ms: u64,
    },
    /// A task within a plan started executing.
    TaskStarted {
        /// The parent plan (denormalization drift carve-out).
        plan_id: String,
        /// The task that started.
        task_id: String,
        /// The agent executing the task.
        agent_id: String,
    },
    /// A task within a plan completed.
    TaskCompleted {
        /// The parent plan (denormalization drift carve-out).
        plan_id: String,
        /// The completed task.
        task_id: String,
        /// Task execution time in milliseconds.
        duration_ms: u64,
    },
    /// A task within a plan failed.
    TaskFailed {
        /// The parent plan (denormalization drift carve-out).
        plan_id: String,
        /// The failed task.
        task_id: String,
        /// Error description.
        error: String,
        /// How many times this task has failed.
        failure_count: u32,
    },
    /// A task was skipped (e.g., HITL chose to skip after escalation, or
    /// preconditions weren't met).
    TaskSkipped {
        /// The parent plan (denormalization drift carve-out).
        plan_id: String,
        /// The skipped task.
        task_id: String,
        /// Free-text reason.
        reason: String,
    },
    /// A task was rolled back to a prior snapshot. M04 Stage B keeps this
    /// as a typed event with `snapshot_id` (drift carve-out vs spec §4a's
    /// stringly-typed error pattern; CLAUDE.md §9 anti-pattern).
    TaskRolledBack {
        /// The parent plan (denormalization drift carve-out).
        plan_id: String,
        /// The rolled-back task.
        task_id: String,
        /// Snapshot used for rollback.
        snapshot_id: String,
    },
    /// A task was escalated (e.g., to a human). M04 Stage B reconciled to
    /// spec §3a shape: replaces `reason` with `failure_count` +
    /// `max_failures` (the FSM emits this once `failure_count >=
    /// max_failures`).
    TaskEscalated {
        /// The parent plan (denormalization drift carve-out).
        plan_id: String,
        /// The escalated task.
        task_id: String,
        /// How many failures triggered escalation.
        failure_count: u32,
        /// Failure budget the task exceeded.
        max_failures: u32,
    },

    // ── Mode (spec §3b) ──
    /// The active mode changed.
    ModeChanged {
        /// Previous mode.
        from: String,
        /// New mode.
        to: String,
        /// Reason for the change.
        reason: String,
    },

    // ── Verify + Rails (spec §4a) ──
    /// A verification hook started. Spec §4a `hook_started`; the codebase
    /// retains the `verify_*` variant naming per M04.D audit decision (the
    /// Hook *primitive* in `common.v1.json` keeps "hook" terminology;
    /// the *event variants* stay as `verify_*` per existing convention).
    VerifyStarted {
        /// Hook identifier (matches `Hook.id` in framework JSON).
        hook_id: String,
        /// Hook category — `verify | lint | build | test | custom`.
        category: String,
        /// Lifecycle moment that fired this hook (one of the 7 firing
        /// points in `framework.v1.json` `hooks`).
        firing_point: String,
        /// Optional verification grouping — `quick | standard | full`.
        level: Option<String>,
    },
    /// A verification hook passed.
    VerifyPassed {
        /// Hook identifier.
        hook_id: String,
        /// Verification duration in milliseconds.
        duration_ms: u64,
        /// Optional preview of the hook's stdout (truncated; spec §4a).
        output_preview: Option<String>,
    },
    /// A verification hook failed.
    VerifyFailed {
        /// Hook identifier.
        hook_id: String,
        /// Verification duration in milliseconds.
        duration_ms: u64,
        /// Error description.
        error: String,
        /// `on_failure` policy from the framework JSON — `block | warn |
        /// rollback`. Drives the SDK / drone follow-up: rollback dispatches
        /// `DroneCommand::RevertToSnapshot { reason: HookRollback }`.
        on_failure: String,
    },
    /// A rail was triggered.
    RailTriggered {
        /// Rail identifier.
        rail_id: String,
        /// Rail policy — `hard` (block) or `soft` (warn). Spec §4a.
        policy: String,
        /// Firing point that produced this trigger.
        firing_point: String,
        /// Human-readable message.
        message: String,
        /// Agent that attempted the action (when applicable).
        agent_id: Option<String>,
    },

    // ── Gap detection (spec §4b) ──
    /// A required skill is missing. M05.A added `suggested_action` +
    /// `requested_via` per spec §4b severity matrix; severity tightened
    /// from free-string to [`GapSeverityRef`].
    SkillMissing {
        /// The agent that needs the skill.
        agent_id: String,
        /// Name of the missing skill.
        skill_name: String,
        /// Severity per spec §4b severity matrix.
        severity: GapSeverityRef,
        /// Plain-English next-step text the renderer surfaces. minLength 1
        /// per schema; emitters compose non-empty per gap kind.
        suggested_action: String,
        /// Layer-1 (`loader`) or Layer-2 (`request_capability`) origin.
        requested_via: GapSourceRef,
    },
    /// A required tool is missing. M05.A added `suggested_action` +
    /// `requested_via` per spec §4b severity matrix; severity tightened
    /// from free-string to [`GapSeverityRef`].
    ToolMissing {
        /// The agent that needs the tool.
        agent_id: String,
        /// Name of the missing tool.
        tool_name: String,
        /// Severity per spec §4b severity matrix.
        severity: GapSeverityRef,
        /// Plain-English next-step text the renderer surfaces. minLength 1
        /// per schema; emitters compose non-empty per gap kind.
        suggested_action: String,
        /// Layer-1 (`loader`) or Layer-2 (`request_capability`) origin.
        requested_via: GapSourceRef,
    },
    /// An MCP server reference is missing — spec §4b + §5. v0.1 emits this
    /// only from Layer 2 `request_capability`; M06 adds Layer-1 emission
    /// once the framework schema declares MCP servers explicitly.
    McpMissing {
        /// The agent that needs the MCP server.
        agent_id: String,
        /// Name of the missing MCP server.
        server_name: String,
        /// Severity per spec §4b severity matrix.
        severity: GapSeverityRef,
        /// Plain-English next-step text the renderer surfaces.
        suggested_action: String,
        /// Layer-1 (`loader`) or Layer-2 (`request_capability`) origin.
        requested_via: GapSourceRef,
    },
    /// A `spawns[]` reference is unresolved — spec §4b Layer 1. Per spec
    /// §4b severity matrix this is a load-time block: framework fails to
    /// load. Also emittable from Layer 2 when an agent asks for a
    /// sub-agent it cannot spawn.
    AgentMissing {
        /// The parent agent whose `spawns[]` references the missing id.
        agent_id: String,
        /// Id of the missing sub-agent.
        missing_agent_id: String,
        /// Severity per spec §4b severity matrix.
        severity: GapSeverityRef,
        /// Plain-English next-step text the renderer surfaces.
        suggested_action: String,
        /// Layer-1 (`loader`) or Layer-2 (`request_capability`) origin.
        requested_via: GapSourceRef,
    },
    /// A previously detected gap was resolved.
    GapResolved {
        /// The agent whose gap was resolved.
        agent_id: String,
        /// The capability that was provided.
        capability: String,
        /// Kind of capability (tool / skill / mcp / agent).
        kind: String,
    },

    // ── HITL (spec §6a) ──
    /// A HITL trigger fired. M04 Stage E aligned this variant to the spec
    /// §6a `HitlNotifyEvent` shape: `prompt_id` (correlation id for resolve),
    /// `trigger` (which of 9), `question`, `options[]`, `ui_variant`, timeout.
    /// The M03 minimal shape (`prompt` + `hitl_kind`) had no live producers and
    /// is replaced; the rename is documented as ambiguity-event in M04.E retro.
    HitlRequested {
        /// Correlation id (UUID) tying this request to the eventual
        /// `hitl_resolved` / `hitl_timeout`. The renderer passes this back
        /// via `respond_hitl(prompt_id, choice)`.
        prompt_id: String,
        /// Which of the 9 HITL triggers fired (spec §6a).
        trigger: HitlTriggerRef,
        /// Originating agent, when applicable. `per_task` / `per_epic` are
        /// plan-level — `agent_id` is `None` in those cases.
        agent_id: Option<String>,
        /// User-facing question.
        question: String,
        /// Expected choice tokens. Empty array means free-text response.
        options: Vec<String>,
        /// UI variant the renderer should mount.
        ui_variant: HitlUiVariantRef,
        /// Wall-clock deadline (unix milliseconds).
        timeout_at_unix_ms: u64,
    },
    /// A HITL prompt was resolved by user response.
    HitlResolved {
        /// Correlation id matching the originating [`AgentEvent::HitlRequested`].
        prompt_id: String,
        /// Selected token; one of the originating `options[]`, or free-text
        /// when `options[]` was empty.
        choice: String,
        /// How long the user took to respond, in milliseconds.
        duration_ms: u64,
    },
    /// A HITL prompt's `timeout_at_unix_ms` elapsed without a response.
    /// The `default_action_on_timeout` from framework JSON drives downstream
    /// FSM transitions.
    HitlTimeout {
        /// Correlation id of the timed-out prompt.
        prompt_id: String,
        /// Which trigger fired the original prompt.
        trigger: HitlTriggerRef,
        /// Free-text action token from framework JSON (e.g. `"abort"`).
        default_action: String,
    },
    /// A notifier successfully fired for a HITL request.
    NotifierDispatched {
        /// Notifier type (`terminal_bell`, `desktop`, `sound`, `plugin`).
        notifier_type: String,
        /// Trigger that produced the originating HITL request.
        trigger: HitlTriggerRef,
        /// Always `true` when this variant is emitted; carried for parity
        /// with the renderer's exhaustive narrow.
        success: bool,
    },
    /// A notifier raised an error (e.g. desktop notification permission
    /// denied). Notifier failures are NON-FATAL — the seam still resolves
    /// on user response or timeout regardless of which notifiers fired.
    NotifierFailed {
        /// Notifier type that failed.
        notifier_type: String,
        /// Trigger that produced the originating HITL request.
        trigger: HitlTriggerRef,
        /// Human-readable error text.
        error: String,
    },

    // ── Capability enforcement (spec §8.security L1+L2a — M05 Stage B) ──
    /// An agent's tool dispatch or sub-agent spawn was rejected by the
    /// §8.security L2a enforcer.
    ///
    /// Emitted BEFORE the `on_capability_violation` HITL prompt fires so
    /// the renderer surfaces state immediately (gotcha trap #4 — emission
    /// ordering matters for renderer responsiveness).
    CapabilityViolation {
        /// Agent whose dispatch the enforcer rejected.
        agent_id: String,
        /// Coarse category of access the attempted dispatch needed.
        capability_kind: CapabilityKindRef,
        /// Plain-English description of what the agent attempted; surfaced
        /// in the HITL prompt + capability-violation modal so the user
        /// understands the rejection.
        requested_action: String,
        /// Plain-English description of the scope the agent's grants
        /// cover. Renderer pairs with `requested_action` to surface the
        /// mismatch (e.g., grants cover `src/**` glob; request targeted
        /// `~/.ssh/keys`).
        declared_scope: String,
    },
    /// A capability was granted to an agent — either at framework load
    /// (root grant; `parent_agent_id` absent) or via L2a narrowing on a
    /// sub-agent spawn (`parent_agent_id` present).
    CapabilityGrant {
        /// Optional — agent whose grants this grant narrows from. Absent
        /// for framework-loader-issued root grants; present whenever an
        /// agent spawns a sub-agent and narrows a subset of its grants
        /// to the child.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        parent_agent_id: Option<String>,
        /// Agent receiving the grant.
        granted_to: String,
        /// Coarse category of access the grant covers.
        capability_kind: CapabilityKindRef,
        /// Resource name the grant covers — tool name, file glob,
        /// hostname, or sub-agent id depending on `capability_kind`.
        resource: String,
        /// Optional — plain-English description of the parent's broader
        /// scope. Renderer uses this in the inspector to show "narrowed
        /// from ... to ..." attribution; absent for root grants.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        narrowed_from: Option<String>,
    },

    // ── Tier system (spec §8.security L4 — M05 Stage D) ──
    /// The L4 tier gate rejected an agent's dispatch BEFORE the L1
    /// enforcer ran. Distinct from `CapabilityViolation` (L1) — the
    /// renderer routes this to a tier-violation modal in the Settings
    /// panel.
    TierViolation {
        /// Agent whose dispatch the L4 evaluator rejected.
        agent_id: String,
        /// The tier that rejected the request.
        tier: TierRef,
        /// The coarse kind the tier's allowlist excludes.
        capability_kind: CapabilityKindRef,
        /// Plain-English description of what the agent attempted.
        attempted_action: String,
    },
    /// The user's tier changed. Emitted after the persistence layer
    /// commits the new tier to `tier.json` so the renderer's graph
    /// store can update `currentTier` and the Settings panel toggle
    /// reflects the new state.
    TierTransition {
        /// The tier the user was on before the transition.
        previous: TierRef,
        /// The tier the user is now on.
        current: TierRef,
        /// Plain-English reason — confirmation copy / demote-on-uncertainty
        /// trigger / etc.
        reason: String,
    },

    // ── Budget (spec §2a) ──
    /// Budget warning threshold reached.
    BudgetWarn {
        /// Amount spent so far in USD.
        spent_usd: f64,
        /// Budget cap in USD.
        cap_usd: f64,
        /// Percentage of budget used.
        percent: u32,
    },
    /// Budget triggered a model downshift.
    BudgetDownshift {
        /// Model being downshifted from.
        from_model: String,
        /// Model being downshifted to.
        to_model: String,
        /// Reason for the downshift.
        reason: String,
    },
    /// Session suspended due to budget.
    BudgetSuspended {
        /// Amount spent so far in USD.
        spent_usd: f64,
        /// Budget cap in USD.
        cap_usd: f64,
    },
    /// Budget exceeded.
    BudgetExceeded {
        /// Amount spent so far in USD.
        spent_usd: f64,
        /// Budget cap in USD.
        cap_usd: f64,
    },

    // ── Stream + decision trace (spec §2 + §2b) ──
    /// Streaming text from an agent.
    StreamText {
        /// The streaming agent.
        agent_id: String,
        /// The text chunk.
        text: String,
    },
    /// A decision was recorded in the VDR.
    DecisionRecord {
        /// The agent that made the decision.
        agent_id: String,
        /// What was decided.
        decision: String,
        /// Why it was decided.
        rationale: String,
        /// Tool used, if any.
        tool_used: Option<String>,
    },
    /// Token usage report.
    TokenUsage {
        /// Input tokens consumed.
        input: u64,
        /// Output tokens produced.
        output: u64,
        /// Model used.
        model: String,
        /// Estimated cost in USD.
        cost_usd: f64,
    },
    /// A short MCP tool name became ambiguous on re-resolution — spec §5a
    /// step 5 (M06.D). Emitted when a server connect makes a
    /// previously-unambiguous short name resolve to >1 candidate across
    /// the connected-server set. The framework pins it via `mcp_aliases`
    /// to silence the warning. Renderer surfaces a warning toast.
    ToolAliasAmbiguous {
        /// The short tool name that is now ambiguous.
        name: String,
        /// The ≥2 canonical `<server>__<tool>` candidates it matched.
        candidates: Vec<String>,
    },
    /// An MCP tool dispatch was denied by the L1+L4 capability check —
    /// spec §5a + §8.security (M06.D). Emitted alongside
    /// `CapabilityViolation` on a single deny; carries the resolved MCP
    /// server + tool so the renderer attributes the block to the `MCPNode`.
    McpRequestBlocked {
        /// Agent whose MCP dispatch the enforcer rejected.
        agent_id: String,
        /// Resolved MCP server name.
        server: String,
        /// Resolved MCP tool name.
        tool: String,
        /// Human-readable deny cause (rendered verbatim).
        reason: String,
    },

    // ── Registry import integrity (spec §2181-2216, M07 Stage B) ──
    /// An installed artifact's recomputed SRI content hash no longer
    /// matches the hash locked in `skills.lock` — spec §2214; ADR-0014.
    /// The load path BLOCKS the artifact's use (integrity > availability)
    /// and the renderer surfaces a Reinstall / Remove prompt (M07 Stage
    /// E). Mirrors `event.v1.json` `ArtifactHashMismatch`; hand-rolled
    /// here per the `BudgetWarn` / `McpRequestBlocked` curated-union
    /// precedent (typify generates the parallel artifact).
    ArtifactHashMismatch {
        /// `name@version` of the drifted artifact.
        artifact_ref: String,
        /// The SRI hash recorded in `skills.lock` at install time.
        expected: String,
        /// The SRI hash recomputed over the bytes on disk now.
        actual: String,
    },
}

#[cfg(test)]
mod proptest_round_trip {
    use super::*;
    use proptest::prelude::*;

    fn arb_session_start() -> impl Strategy<Value = AgentEvent> {
        (any::<String>(), any::<String>(), any::<String>()).prop_map(
            |(session_id, framework, model)| AgentEvent::SessionStart {
                session_id,
                framework,
                model,
            },
        )
    }

    fn arb_tool_source() -> impl Strategy<Value = ToolSource> {
        prop_oneof![
            Just(ToolSource::Builtin),
            Just(ToolSource::Mcp),
            Just(ToolSource::Generated),
        ]
    }

    fn arb_tool_invoked() -> impl Strategy<Value = AgentEvent> {
        (
            any::<String>(),
            any::<String>(),
            arb_tool_source(),
            proptest::option::of(any::<String>()),
        )
            .prop_map(
                |(agent_id, tool_name, source, server)| AgentEvent::ToolInvoked {
                    agent_id,
                    tool_name,
                    source,
                    server,
                    input: serde_json::json!({"key": "value"}),
                },
            )
    }

    fn arb_agent_spawned() -> impl Strategy<Value = AgentEvent> {
        (
            any::<String>(),
            any::<String>(),
            proptest::option::of(any::<String>()),
            any::<String>(),
        )
            .prop_map(|(agent_id, agent_name, parent_id, session_id)| {
                AgentEvent::AgentSpawned {
                    agent_id,
                    agent_name,
                    parent_id,
                    session_id,
                    // Proptest spawns are exclusively serialization
                    // round-trip fixtures; they do not exercise the
                    // L2a narrowing path. Empty Vec round-trips as
                    // "absent" via skip_serializing_if.
                    narrowed_from: Vec::new(),
                }
            })
    }

    proptest! {
        #[test]
        fn session_start_round_trips(event in arb_session_start()) {
            let json: serde_json::Value = serde_json::to_value(&event).unwrap();
            let back: AgentEvent = serde_json::from_value(json).unwrap();
            prop_assert_eq!(event, back);
        }

        #[test]
        fn tool_invoked_round_trips(event in arb_tool_invoked()) {
            let json: serde_json::Value = serde_json::to_value(&event).unwrap();
            let back: AgentEvent = serde_json::from_value(json).unwrap();
            prop_assert_eq!(event, back);
        }

        #[test]
        fn agent_spawned_round_trips(event in arb_agent_spawned()) {
            let json: serde_json::Value = serde_json::to_value(&event).unwrap();
            let back: AgentEvent = serde_json::from_value(json).unwrap();
            prop_assert_eq!(event, back);
        }

        // Newline-delimited JSON codec round trip — the wire format used by
        // the SSE event pipeline (`tokio_util::codec::LinesCodec`).
        #[test]
        fn agent_event_codec_round_trip_proptest(event in arb_session_start()) {
            let line = serde_json::to_string(&event).unwrap();
            prop_assert!(!line.contains('\n'));
            let back: AgentEvent = serde_json::from_str(&line).unwrap();
            prop_assert_eq!(event, back);
        }
    }
}
